/*******************************************************************************
* Copyright (C) 2026 the Eclipse BaSyx Authors and Fraunhofer IESE
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
* LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* SPDX-License-Identifier: MIT
******************************************************************************/
// Author: Jannik Fried ( Fraunhofer IESE ), Aaron Zielstorff ( Fraunhofer IESE )

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Digital Product Passport API
 *
 * Digital Product Passport API aligned with the IDTA-01001 v3.2 DPP metamodel annex and the IDTA-01002 v3.2 DPP API mapping annex.
 *
 * API version: 1.0.0
 */

package dppapi

import (
	"fmt"
)

// XsdValueDataType : EN 18223 value data type using the xsd prefix.
type XsdValueDataType string

// List of XsdValueDataType
const (
	XSDVALUEDATATYPE_XSD_STRING               XsdValueDataType = "xsd:string"
	XSDVALUEDATATYPE_XSD_BOOLEAN              XsdValueDataType = "xsd:boolean"
	XSDVALUEDATATYPE_XSD_DECIMAL              XsdValueDataType = "xsd:decimal"
	XSDVALUEDATATYPE_XSD_FLOAT                XsdValueDataType = "xsd:float"
	XSDVALUEDATATYPE_XSD_DOUBLE               XsdValueDataType = "xsd:double"
	XSDVALUEDATATYPE_XSD_DURATION             XsdValueDataType = "xsd:duration"
	XSDVALUEDATATYPE_XSD_DATE_TIME            XsdValueDataType = "xsd:dateTime"
	XSDVALUEDATATYPE_XSD_TIME                 XsdValueDataType = "xsd:time"
	XSDVALUEDATATYPE_XSD_DATE                 XsdValueDataType = "xsd:date"
	XSDVALUEDATATYPE_XSD_G_YEAR_MONTH         XsdValueDataType = "xsd:gYearMonth"
	XSDVALUEDATATYPE_XSD_G_YEAR               XsdValueDataType = "xsd:gYear"
	XSDVALUEDATATYPE_XSD_G_MONTH_DAY          XsdValueDataType = "xsd:gMonthDay"
	XSDVALUEDATATYPE_XSD_G_DAY                XsdValueDataType = "xsd:gDay"
	XSDVALUEDATATYPE_XSD_G_MONTH              XsdValueDataType = "xsd:gMonth"
	XSDVALUEDATATYPE_XSD_HEX_BINARY           XsdValueDataType = "xsd:hexBinary"
	XSDVALUEDATATYPE_XSD_BASE64_BINARY        XsdValueDataType = "xsd:base64Binary"
	XSDVALUEDATATYPE_XSD_ANY_URI              XsdValueDataType = "xsd:anyURI"
	XSDVALUEDATATYPE_XSD_Q_NAME               XsdValueDataType = "xsd:QName"
	XSDVALUEDATATYPE_XSD_NOTATION             XsdValueDataType = "xsd:NOTATION"
	XSDVALUEDATATYPE_XSD_NORMALIZED_STRING    XsdValueDataType = "xsd:normalizedString"
	XSDVALUEDATATYPE_XSD_TOKEN                XsdValueDataType = "xsd:token"
	XSDVALUEDATATYPE_XSD_LANGUAGE             XsdValueDataType = "xsd:language"
	XSDVALUEDATATYPE_XSD_NMTOKEN              XsdValueDataType = "xsd:NMTOKEN"
	XSDVALUEDATATYPE_XSD_NMTOKENS             XsdValueDataType = "xsd:NMTOKENS"
	XSDVALUEDATATYPE_XSD_NAME                 XsdValueDataType = "xsd:Name"
	XSDVALUEDATATYPE_XSD_NC_NAME              XsdValueDataType = "xsd:NCName"
	XSDVALUEDATATYPE_XSD_ID                   XsdValueDataType = "xsd:ID"
	XSDVALUEDATATYPE_XSD_IDREF                XsdValueDataType = "xsd:IDREF"
	XSDVALUEDATATYPE_XSD_IDREFS               XsdValueDataType = "xsd:IDREFS"
	XSDVALUEDATATYPE_XSD_ENTITY               XsdValueDataType = "xsd:ENTITY"
	XSDVALUEDATATYPE_XSD_ENTITIES             XsdValueDataType = "xsd:ENTITIES"
	XSDVALUEDATATYPE_XSD_INTEGER              XsdValueDataType = "xsd:integer"
	XSDVALUEDATATYPE_XSD_NON_POSITIVE_INTEGER XsdValueDataType = "xsd:nonPositiveInteger"
	XSDVALUEDATATYPE_XSD_NEGATIVE_INTEGER     XsdValueDataType = "xsd:negativeInteger"
	XSDVALUEDATATYPE_XSD_LONG                 XsdValueDataType = "xsd:long"
	XSDVALUEDATATYPE_XSD_INT                  XsdValueDataType = "xsd:int"
	XSDVALUEDATATYPE_XSD_SHORT                XsdValueDataType = "xsd:short"
	XSDVALUEDATATYPE_XSD_BYTE                 XsdValueDataType = "xsd:byte"
	XSDVALUEDATATYPE_XSD_NON_NEGATIVE_INTEGER XsdValueDataType = "xsd:nonNegativeInteger"
	XSDVALUEDATATYPE_XSD_UNSIGNED_LONG        XsdValueDataType = "xsd:unsignedLong"
	XSDVALUEDATATYPE_XSD_UNSIGNED_INT         XsdValueDataType = "xsd:unsignedInt"
	XSDVALUEDATATYPE_XSD_UNSIGNED_SHORT       XsdValueDataType = "xsd:unsignedShort"
	XSDVALUEDATATYPE_XSD_UNSIGNED_BYTE        XsdValueDataType = "xsd:unsignedByte"
	XSDVALUEDATATYPE_XSD_POSITIVE_INTEGER     XsdValueDataType = "xsd:positiveInteger"
)

// AllowedXsdValueDataTypeEnumValues is all the allowed values of XsdValueDataType enum
var AllowedXsdValueDataTypeEnumValues = []XsdValueDataType{
	"xsd:string",
	"xsd:boolean",
	"xsd:decimal",
	"xsd:float",
	"xsd:double",
	"xsd:duration",
	"xsd:dateTime",
	"xsd:time",
	"xsd:date",
	"xsd:gYearMonth",
	"xsd:gYear",
	"xsd:gMonthDay",
	"xsd:gDay",
	"xsd:gMonth",
	"xsd:hexBinary",
	"xsd:base64Binary",
	"xsd:anyURI",
	"xsd:QName",
	"xsd:NOTATION",
	"xsd:normalizedString",
	"xsd:token",
	"xsd:language",
	"xsd:NMTOKEN",
	"xsd:NMTOKENS",
	"xsd:Name",
	"xsd:NCName",
	"xsd:ID",
	"xsd:IDREF",
	"xsd:IDREFS",
	"xsd:ENTITY",
	"xsd:ENTITIES",
	"xsd:integer",
	"xsd:nonPositiveInteger",
	"xsd:negativeInteger",
	"xsd:long",
	"xsd:int",
	"xsd:short",
	"xsd:byte",
	"xsd:nonNegativeInteger",
	"xsd:unsignedLong",
	"xsd:unsignedInt",
	"xsd:unsignedShort",
	"xsd:unsignedByte",
	"xsd:positiveInteger",
}

// validXsdValueDataTypeEnumValue provides a map of XsdValueDataTypes for fast verification of use input
var validXsdValueDataTypeEnumValues = map[XsdValueDataType]struct{}{
	"xsd:string":             {},
	"xsd:boolean":            {},
	"xsd:decimal":            {},
	"xsd:float":              {},
	"xsd:double":             {},
	"xsd:duration":           {},
	"xsd:dateTime":           {},
	"xsd:time":               {},
	"xsd:date":               {},
	"xsd:gYearMonth":         {},
	"xsd:gYear":              {},
	"xsd:gMonthDay":          {},
	"xsd:gDay":               {},
	"xsd:gMonth":             {},
	"xsd:hexBinary":          {},
	"xsd:base64Binary":       {},
	"xsd:anyURI":             {},
	"xsd:QName":              {},
	"xsd:NOTATION":           {},
	"xsd:normalizedString":   {},
	"xsd:token":              {},
	"xsd:language":           {},
	"xsd:NMTOKEN":            {},
	"xsd:NMTOKENS":           {},
	"xsd:Name":               {},
	"xsd:NCName":             {},
	"xsd:ID":                 {},
	"xsd:IDREF":              {},
	"xsd:IDREFS":             {},
	"xsd:ENTITY":             {},
	"xsd:ENTITIES":           {},
	"xsd:integer":            {},
	"xsd:nonPositiveInteger": {},
	"xsd:negativeInteger":    {},
	"xsd:long":               {},
	"xsd:int":                {},
	"xsd:short":              {},
	"xsd:byte":               {},
	"xsd:nonNegativeInteger": {},
	"xsd:unsignedLong":       {},
	"xsd:unsignedInt":        {},
	"xsd:unsignedShort":      {},
	"xsd:unsignedByte":       {},
	"xsd:positiveInteger":    {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v XsdValueDataType) IsValid() bool {
	_, ok := validXsdValueDataTypeEnumValues[v]
	return ok
}

// NewXsdValueDataTypeFromValue returns a pointer to a valid XsdValueDataType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewXsdValueDataTypeFromValue(v string) (XsdValueDataType, error) {
	ev := XsdValueDataType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for XsdValueDataType: valid values are %v", v, AllowedXsdValueDataTypeEnumValues)
}

// AssertXsdValueDataTypeRequired checks if the required fields are not zero-ed
func AssertXsdValueDataTypeRequired(obj XsdValueDataType) error {
	return nil
}

// AssertXsdValueDataTypeConstraints checks if the values respects the defined constraints
func AssertXsdValueDataTypeConstraints(obj XsdValueDataType) error {
	return nil
}
