/*******************************************************************************
* Copyright (C) 2026 the Eclipse BaSyx Authors and Fraunhofer IESE
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
* LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* SPDX-License-Identifier: MIT
******************************************************************************/
// Author: Jannik Fried ( Fraunhofer IESE ), Aaron Zielstorff ( Fraunhofer IESE )

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Digital Product Passport API
 *
 * Digital Product Passport API aligned with the IDTA-01001 v3.2 DPP metamodel annex and the IDTA-01002 v3.2 DPP API mapping annex.
 *
 * API version: 1.0.0
 */

package dppapi

import (
	"time"
)

type RegisterProductDppRequest struct {
	DigitalProductPassportId string `json:"digitalProductPassportId"`

	UniqueProductIdentifier string `json:"uniqueProductIdentifier"`

	// URL where the DPP can be accessed.
	AccessUrl string `json:"accessUrl"`

	RegistrationTimestamp time.Time `json:"registrationTimestamp,omitempty"`
}

// AssertRegisterProductDppRequestRequired checks if the required fields are not zero-ed
func AssertRegisterProductDppRequestRequired(obj RegisterProductDppRequest) error {
	elements := map[string]interface{}{
		"digitalProductPassportId": obj.DigitalProductPassportId,
		"uniqueProductIdentifier":  obj.UniqueProductIdentifier,
		"accessUrl":                obj.AccessUrl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegisterProductDppRequestConstraints checks if the values respects the defined constraints
func AssertRegisterProductDppRequestConstraints(obj RegisterProductDppRequest) error {
	return nil
}
