/*******************************************************************************
* Copyright (C) 2026 the Eclipse BaSyx Authors and Fraunhofer IESE
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
* LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* SPDX-License-Identifier: MIT
******************************************************************************/
// Author: Jannik Fried ( Fraunhofer IESE ), Aaron Zielstorff ( Fraunhofer IESE )

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Digital Product Passport API
 *
 * Digital Product Passport API aligned with the IDTA-01001 v3.2 DPP metamodel annex and the IDTA-01002 v3.2 DPP API mapping annex.
 *
 * API version: 1.0.0
 */

package dppapi

import (
	"time"
)

// DigitalProductPassport - A single DPP JSON document composed from the DppMetadata header and one or more content Submodel sections. Content section property names shall use the contributing Submodel idShort with the first letter in lower case, and contentSpecificationIds shall list the corresponding content Submodel semantic identifiers.
type DigitalProductPassport struct {

	// DPP identifier. Similar to, but not necessarily identical to, the AAS id.
	DigitalProductPassportId string `json:"digitalProductPassportId"`

	// Product identifier corresponding to the AAS AssetInformation globalAssetId.
	UniqueProductIdentifier string `json:"uniqueProductIdentifier"`

	Granularity Granularity `json:"granularity"`

	DppSchemaVersion string `json:"dppSchemaVersion"`

	DppStatus string `json:"dppStatus"`

	// Timestamp corresponding to AAS AdministrativeInformation updatedAt.
	LastUpdate time.Time `json:"lastUpdate"`

	// Economic operator identifier as specified by EN 18219.
	EconomicOperatorId string `json:"economicOperatorId"`

	// Facility identifier as specified by EN 18219.
	FacilityId string `json:"facilityId"`

	// Semantic identifiers of contributing content Submodels. The DPP document shall contain matching top-level content sections.
	ContentSpecificationIds []string `json:"contentSpecificationIds"`
}

// AssertDigitalProductPassportRequired checks if the required fields are not zero-ed
func AssertDigitalProductPassportRequired(obj DigitalProductPassport) error {
	elements := map[string]interface{}{
		"digitalProductPassportId": obj.DigitalProductPassportId,
		"uniqueProductIdentifier":  obj.UniqueProductIdentifier,
		"granularity":              obj.Granularity,
		"dppSchemaVersion":         obj.DppSchemaVersion,
		"dppStatus":                obj.DppStatus,
		"lastUpdate":               obj.LastUpdate,
		"economicOperatorId":       obj.EconomicOperatorId,
		"facilityId":               obj.FacilityId,
		"contentSpecificationIds":  obj.ContentSpecificationIds,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDigitalProductPassportConstraints checks if the values respects the defined constraints
func AssertDigitalProductPassportConstraints(obj DigitalProductPassport) error {
	return nil
}
