services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxTestDB
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxTestDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - basyx-java-server-sdk

  discoveryservice:
    build:
      context: ../../../..
      dockerfile: ./cmd/discoveryservice/Dockerfile
      
    environment:
      - SERVER_PORT=5004
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
    ports:
      - "5004:5004"
    depends_on:
      db:
        condition: service_healthy
      keycloak-healthcheck:
        condition: service_completed_successfully
    networks:
      - basyx-java-server-sdk

  keycloak-abac:
    image: keycloak/keycloak:26.0.6
    container_name: keycloak-abac
    environment:
      VIRTUAL_HOST: keycloak.basyx.localhost
      VIRTUAL_PORT: "8080"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/basyxTestDB
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin123
      KC_HOSTNAME: keycloak.basyx.localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_IMPORT: /opt/keycloak/data/import/
      KC_HTTP_MANAGEMENT_ENABLED: "true"
    command: ["start-dev", "--import-realm", "--health-enabled=true"]
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      basyx-java-server-sdk: 
        aliases:
          - keycloak.basyx.localhost

  keycloak-healthcheck:
    image: curlimages/curl:latest
    container_name: keycloak-healthcheck
    command: >
      sh -c "
        echo 'Waiting for Keycloak to become ready...';
        until curl -sf http://keycloak-abac:9000/health/ready; do
          sleep 5;
        done;
        echo 'Keycloak is ready!'"
    depends_on:
      - keycloak-abac
    networks:
      - basyx-java-server-sdk
  
  
networks:
  basyx-java-server-sdk:
    name: basyx-java-server-sdk
    driver: bridge


