version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: mod

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
     - misspell
     - errcheck
     - govet
     - ineffassign
     - staticcheck
     - revive
     - unused
     - gocritic
