linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - golint
    - govet
    - gocyclo
    - goimports

issues:
  exclude-dirs:
    - pkg/discoveryapi/go
