version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
     - misspell
     - errcheck
     - govet
     - ineffassign
     - staticcheck
     - revive
     - unused
     - gocritic
     - gosec
     
  settings:
    revive:
      rules:
        - name: argument-limit
          arguments: [6]
        - name: cognitive-complexity
          arguments: [30]   # Warn if function is too complex
        - name: cyclomatic
          arguments: [20]   # Max allowed cyclomatic complexity
        - name: deep-exit   # Disallow early os.Exit in functions
        - name: errorf      # Use fmt.Errorf instead of fmt.Sprintf for errors
        - name: unhandled-error
        - name: redefines-builtin-id  # Prevent redefining built-in names like 'error' or 'string'
        - name: unused-parameter
        - name: unreachable-code

      # code style
        - name: indent-error-flow
        - name: if-return
        - name: early-return
          arguments: ["ID", "Id"]  # Allow common initialisms like ID, URL, HTTP, JSON
        - name: package-comments
        - name: exported
        - name: line-length-limit
          arguments: [120]
        - name: empty-block
        - name: empty-lines

      # performance
        - name: constant-logical-expr
        - name: range-val-in-closure
        - name: range-val-address
        - name: import-shadowing
        - name: context-as-argument  # Encourage passing context.Context as first param
        - name: struct-tag
        - name: receiver-naming
        - name: bare-return          # Discourage bare returns
      
      # best practices
        - name: defer
        - name: error-return
        - name: error-naming
        - name: unnecessary-stmt
        - name: redundant-import-alias
        - name: modifies-parameter
        - name: atomic
        - name: time-naming
