services:
  aas-registry:
    container_name: aas-registry
    image: eclipsebasyx/aasregistry-go:SNAPSHOT
    ports:
      - 8082:5004
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=false
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  
  sm-registry:
    container_name: sm-registry
    image: eclipsebasyx/submodelregistry-go:SNAPSHOT
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=false
    ports:
      - 8083:5004
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  aas-discovery:
    container_name: aas-discovery
    image: eclipsebasyx/aasdiscovery-go:SNAPSHOT
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=false
    ports:
      - "8084:5004"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
      
  aas-ui:
    container_name: aas-web-ui
    image: eclipsebasyx/aas-gui:SNAPSHOT
    ports:
      - "3000:3000"
    environment:
      AAS_REGISTRY_PATH: "http://localhost:8082/shell-descriptors"
      SUBMODEL_REGISTRY_PATH: "http://localhost:8083/submodel-descriptors"
      AAS_DISCOVERY_PATH: "http://localhost:8084/lookup/shells"
      AAS_REPO_PATH: "http://localhost:8090/shells"
      SUBMODEL_REPO_PATH: "http://localhost:8091/submodels"
      CD_REPO_PATH: "http://localhost:8092/concept-descriptions"
    restart: unless-stopped

  aas_repository:
    container_name: aas-repository
    image: eclipsebasyx/aasrepository-go:SNAPSHOT
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=false
    ports:
      - "8090:5004"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  submodel_repository:
    container_name: submodel-repository
    image: eclipsebasyx/submodelrepository-go:SNAPSHOT      
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - JWS_PRIVATEKEYPATH=/app/rsa-key.pem
      - ABAC_ENABLED=false
    volumes:
      - ./basyx/rsa-key.pem:/app/rsa-key.pem:ro
    ports:
      - "8091:5004"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  concept-description-repository:
    container_name: concept-description-repository
    image: eclipsebasyx/conceptdescriptionrepository-go:SNAPSHOT
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=false
    ports:
      - "8092:5004"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # PostgreSQL database
  db:
    container_name: postgres_db
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxTestDB
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxTestDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
