services:
  aas-environment:
    container_name: aas-environment
    image: eclipsebasyx/aasenvironment-go:SNAPSHOT
    # pull_policy: always
    command: ["/app/aasenvironmentservice"]
    ports:
      - 8080:5004
    environment:
      - SERVER_PORT=5004
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DBNAME=basyxTestDB
      - POSTGRES_MAXOPENCONNECTIONS=500
      - POSTGRES_MAXIDLECONNECTIONS=500
      - POSTGRES_CONNMAXLIFETIMEMINUTES=5
      - ABAC_ENABLED=false
      - GENERAL_DISCOVERYINTEGRATION=true
    depends_on:
      db-schema-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    restart: unless-stopped
      
  aas-ui:
    container_name: aas-web-ui
    image: eclipsebasyx/aas-gui:SNAPSHOT
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./basyx-infra.yml:/basyx-infra.yml:ro
    environment:
      - ENDPOINT_CONFIG_AVAILABLE=false
    restart: unless-stopped

  db-schema-init:
    image: postgres:18
    container_name: db-schema-init
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxTestDB
    command: ["sh", "/init/init-schema.sh"]
    volumes:
      - ../../basyxschema.sql:/schema/basyxschema.sql:ro
      - ./db_init/init-schema.sh:/init/init-schema.sh:ro
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  # PostgreSQL database
  db:
    container_name: postgres_db
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: basyxTestDB
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d basyxTestDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
