// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Registry Service Specification
 *
 * The Full Profile of the Asset Administration Shell Registry Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) 2025
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */
//nolint:all
package model

import "github.com/FriedJannik/aas-go-sdk/types"

type SubmodelDescriptor struct {
	Administration types.IAdministrativeInformation `json:"administration,omitempty"`

	Endpoints []Endpoint `json:"endpoints"`

	IdShort string `json:"idShort,omitempty" validate:"regexp=^[a-zA-Z][a-zA-Z0-9_-]*[a-zA-Z0-9_]+$"`

	Id string `json:"id" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	SemanticId types.IReference `json:"semanticId,omitempty"`

	SupplementalSemanticId []types.IReference `json:"supplementalSemanticIds,omitempty"`

	Description []types.ILangStringTextType `json:"description,omitempty"`

	DisplayName []types.ILangStringNameType `json:"displayName,omitempty"`

	Extensions []types.Extension `json:"extensions,omitempty"`
}

// AssertSubmodelDescriptorRequired checks if the required fields are not zero-ed
func AssertSubmodelDescriptorRequired(obj SubmodelDescriptor) error {
	elements := map[string]any{
		"endpoints": obj.Endpoints,
		"id":        obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}
	for _, el := range obj.Endpoints {
		if err := AssertEndpointRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSubmodelDescriptorConstraints checks if the values respects the defined constraints
func AssertSubmodelDescriptorConstraints(obj SubmodelDescriptor) error {
	for _, el := range obj.Endpoints {
		if err := AssertEndpointConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
