// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"errors"
	"fmt"

	"github.com/FriedJannik/aas-go-sdk/jsonization"
	"github.com/FriedJannik/aas-go-sdk/types"
	"github.com/FriedJannik/aas-go-sdk/verification"
	jsoniter "github.com/json-iterator/go"
)

type InfrastructureDescriptor struct {
	Description []types.ILangStringTextType `json:"description,omitempty"`

	DisplayName []types.ILangStringNameType `json:"displayName,omitempty"`

	Administration types.IAdministrativeInformation `json:"administration,omitempty"`

	Endpoints []Endpoint `json:"endpoints,omitempty"`

	GlobalAssetId string `json:"globalAssetId,omitempty" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	IdShort string `json:"idShort,omitempty" validate:"regexp=^[a-zA-Z][a-zA-Z0-9_-]*[a-zA-Z0-9_]+$"`

	Id string `json:"id" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	Name string `json:"name,omitempty" validate:"regexp=^[A-Za-z0-9 ._-]*$"`

	Domain string `json:"domain,omitempty" validate:"regexp=^[A-Za-z0-9.-]*$"`

	NameOptions []string `json:"nameOptions,omitempty"`

	AssetIdRegexPatterns []string `json:"assetIdRegexPatterns,omitempty"`

	IdLinkRegexPatterns []string `json:"idLinkRegexPatterns,omitempty"`
}

// AssertInfrastructureDescriptorRequired checks if the required fields are not zero-ed
func AssertInfrastructureDescriptorRequired(obj InfrastructureDescriptor) error {
	elements := map[string]any{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}
	for _, el := range obj.Endpoints {
		if err := AssertEndpointRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertInfrastructureDescriptorConstraints checks if the values respects the defined constraints
func AssertInfrastructureDescriptorConstraints(obj InfrastructureDescriptor) error {
	for _, el := range obj.Endpoints {
		if err := AssertEndpointConstraints(el); err != nil {
			return err
		}
	}

	seen := make(map[string]struct{}, len(obj.NameOptions))
	for i, option := range obj.NameOptions {
		if option == "" {
			return fmt.Errorf("nameOptions[%d] must not be empty", i)
		}
		if _, ok := seen[option]; ok {
			return fmt.Errorf("nameOptions contains duplicate value %q", option)
		}
		seen[option] = struct{}{}
	}

	assetRegexSeen := make(map[string]struct{}, len(obj.AssetIdRegexPatterns))
	for i, pattern := range obj.AssetIdRegexPatterns {
		if pattern == "" {
			return fmt.Errorf("assetIdRegexPatterns[%d] must not be empty", i)
		}
		if _, ok := assetRegexSeen[pattern]; ok {
			return fmt.Errorf("assetIdRegexPatterns contains duplicate value %q", pattern)
		}
		assetRegexSeen[pattern] = struct{}{}
	}

	idLinkRegexSeen := make(map[string]struct{}, len(obj.IdLinkRegexPatterns))
	for i, pattern := range obj.IdLinkRegexPatterns {
		if pattern == "" {
			return fmt.Errorf("idLinkRegexPatterns[%d] must not be empty", i)
		}
		if _, ok := idLinkRegexSeen[pattern]; ok {
			return fmt.Errorf("idLinkRegexPatterns contains duplicate value %q", pattern)
		}
		idLinkRegexSeen[pattern] = struct{}{}
	}
	return nil
}

func (obj InfrastructureDescriptor) ToJsonable() (map[string]any, error) {
	// Marshal every AAS GO SDK Type
	ret := make(map[string]any)
	// Description
	var descriptions []map[string]any
	for _, desc := range obj.Description {
		desc, err := jsonization.ToJsonable(desc)
		if err != nil {
			return nil, err
		}
		descriptions = append(descriptions, desc)
	}

	// Display Name
	var displayNames []map[string]any
	for _, dn := range obj.DisplayName {
		dn, err := jsonization.ToJsonable(dn)
		if err != nil {
			return nil, err
		}
		displayNames = append(displayNames, dn)
	}

	// Administration
	var administration map[string]any
	if obj.Administration != nil {
		var err error
		administration, err = jsonization.ToJsonable(obj.Administration)
		if err != nil {
			return nil, err
		}
	}

	if len(descriptions) > 0 {
		ret["description"] = descriptions
	}
	if len(displayNames) > 0 {
		ret["displayName"] = displayNames
	}
	if administration != nil {
		ret["administration"] = administration
	}
	if len(obj.Endpoints) > 0 {
		ret["endpoints"] = obj.Endpoints
	}
	if obj.IdShort != "" {
		ret["idShort"] = obj.IdShort
	}
	if obj.Id != "" {
		ret["id"] = obj.Id
	}
	if obj.Name != "" {
		ret["name"] = obj.Name
	}
	if obj.Domain != "" {
		ret["domain"] = obj.Domain
	}
	if len(obj.NameOptions) > 0 {
		ret["nameOptions"] = obj.NameOptions
	}
	if len(obj.AssetIdRegexPatterns) > 0 {
		ret["assetIdRegexPatterns"] = obj.AssetIdRegexPatterns
	}
	if len(obj.IdLinkRegexPatterns) > 0 {
		ret["idLinkRegexPatterns"] = obj.IdLinkRegexPatterns
	}
	return ret, nil
}

// UnmarshalJSON implements custom unmarshaling for SubmodelDescriptor
// It handles the FromJsonable Unmarshalling of the aas-go-sdk types
func (obj *InfrastructureDescriptor) UnmarshalJSON(data []byte) error {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var jsonable map[string]any
	if err := json.Unmarshal(data, &jsonable); err != nil {
		return err
	}

	// Check for unknown fields
	allowedFields := map[string]bool{
		"administration":       true,
		"endpoints":            true,
		"idShort":              true,
		"id":                   true,
		"name":                 true,
		"domain":               true,
		"nameOptions":          true,
		"assetIdRegexPatterns": true,
		"idLinkRegexPatterns":  true,
		"description":          true,
		"displayName":          true,
		"extensions":           true,
	}
	for key := range jsonable {
		if !allowedFields[key] {
			return errors.New("unknown field: " + key)
		}
	}

	// Description
	if descs, ok := jsonable["description"].([]any); ok {
		for _, desc := range descs {
			descMap, ok := desc.(map[string]any)
			if !ok {
				return errors.New("InfrastructureDescriptor: description is not a map")
			}
			var langString types.ILangStringTextType
			langString, err := jsonization.LangStringTextTypeFromJsonable(descMap)
			if err != nil {
				return err
			}
			obj.Description = append(obj.Description, langString)
		}
	}

	// Display Name
	if dns, ok := jsonable["displayName"].([]any); ok {
		for _, dn := range dns {
			dnMap, ok := dn.(map[string]any)
			if !ok {
				return errors.New("InfrastructureDescriptor: displayName is not a map")
			}
			var langString types.ILangStringNameType
			langString, err := jsonization.LangStringNameTypeFromJsonable(dnMap)
			if err != nil {
				return err
			}
			obj.DisplayName = append(obj.DisplayName, langString)
		}
	}

	// Endpoints
	if eps, ok := jsonable["endpoints"].([]any); ok {
		for _, ep := range eps {
			epMap, ok := ep.(map[string]any)
			if !ok {
				return errors.New("InfrastructureDescriptor: endpoint is not a map")
			}
			var endpoint Endpoint
			endpointBytes, err := json.Marshal(epMap)
			if err != nil {
				return err
			}
			if err := json.Unmarshal(endpointBytes, &endpoint); err != nil {
				return err
			}
			obj.Endpoints = append(obj.Endpoints, endpoint)
		}
	}

	// Administration
	if admin, ok := jsonable["administration"].(map[string]any); ok {
		var administration types.IAdministrativeInformation
		administration, err := jsonization.AdministrativeInformationFromJsonable(admin)
		if err != nil {
			return err
		}
		obj.Administration = administration
	}

	// Handle other simple fields
	if idShort, ok := jsonable["idShort"].(string); ok {
		obj.IdShort = idShort
	}
	if id, ok := jsonable["id"].(string); ok {
		obj.Id = id
	}
	if name, ok := jsonable["name"].(string); ok {
		obj.Name = name
	}
	if domain, ok := jsonable["domain"].(string); ok {
		obj.Domain = domain
	}
	if options, ok := jsonable["nameOptions"].([]any); ok {
		for i, rawOption := range options {
			option, ok := rawOption.(string)
			if !ok {
				return fmt.Errorf("InfrastructureDescriptor: nameOptions[%d] is not a string", i)
			}
			obj.NameOptions = append(obj.NameOptions, option)
		}
	}
	if patterns, ok := jsonable["assetIdRegexPatterns"].([]any); ok {
		for i, rawPattern := range patterns {
			pattern, ok := rawPattern.(string)
			if !ok {
				return fmt.Errorf("InfrastructureDescriptor: assetIdRegexPatterns[%d] is not a string", i)
			}
			obj.AssetIdRegexPatterns = append(obj.AssetIdRegexPatterns, pattern)
		}
	}
	if patterns, ok := jsonable["idLinkRegexPatterns"].([]any); ok {
		for i, rawPattern := range patterns {
			pattern, ok := rawPattern.(string)
			if !ok {
				return fmt.Errorf("InfrastructureDescriptor: idLinkRegexPatterns[%d] is not a string", i)
			}
			obj.IdLinkRegexPatterns = append(obj.IdLinkRegexPatterns, pattern)
		}
	}

	// Verify Description
	var validationErrors []string
	for _, el := range obj.Description {
		verification.Verify(el, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})

		if len(validationErrors) > 0 {
			return errors.New("InfrastructureDescriptor: Description verification failed: " + validationErrors[0])
		}
	}

	// Verify DisplayName
	validationErrors = []string{}
	for _, el := range obj.DisplayName {
		verification.Verify(el, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})

		if len(validationErrors) > 0 {
			return errors.New("InfrastructureDescriptor: DisplayName verification failed: " + validationErrors[0])
		}
	}

	// Administration
	validationErrors = []string{}
	if obj.Administration != nil {
		verification.Verify(obj.Administration, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})
		if len(validationErrors) > 0 {
			return errors.New("InfrastructureDescriptor: Administration verification failed: " + validationErrors[0])
		}
	}

	return nil
}
