// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Asset Administration Shell Registry Service Specification
 *
 * The Query Profile of the Asset Administration Shell Registry Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) 2025
 *
 * API version: V3.1.0_SSP-004
 * Contact: info@idtwin.org
 */

package model

import "time"

type Value struct {
	Field string `json:"$field,omitempty"`

	StrVal string `json:"$strVal,omitempty"`

	NumVal float32 `json:"$numVal,omitempty"`

	HexVal string `json:"$hexVal,omitempty"`

	DateTimeVal time.Time `json:"$dateTimeVal,omitempty"`

	TimeVal string `json:"$timeVal,omitempty"`

	Boolean bool `json:"$boolean,omitempty"`

	StrCast *Value `json:"$strCast,omitempty"`

	NumCast *Value `json:"$numCast,omitempty"`

	HexCast *Value `json:"$hexCast,omitempty"`

	BoolCast *Value `json:"$boolCast,omitempty"`

	DateTimeCast *Value `json:"$dateTimeCast,omitempty"`

	TimeCast *Value `json:"$timeCast,omitempty"`

	DayOfWeek time.Time `json:"$dayOfWeek,omitempty"`

	DayOfMonth time.Time `json:"$dayOfMonth,omitempty"`

	Month time.Time `json:"$month,omitempty"`

	Year time.Time `json:"$year,omitempty"`
}

// AssertValueRequired checks if the required fields are not zero-ed
func AssertValueRequired(obj Value) error {
	if obj.StrCast != nil {
		if err := AssertValueRequired(*obj.StrCast); err != nil {
			return err
		}
	}
	if obj.NumCast != nil {
		if err := AssertValueRequired(*obj.NumCast); err != nil {
			return err
		}
	}
	if obj.HexCast != nil {
		if err := AssertValueRequired(*obj.HexCast); err != nil {
			return err
		}
	}
	if obj.BoolCast != nil {
		if err := AssertValueRequired(*obj.BoolCast); err != nil {
			return err
		}
	}
	if obj.DateTimeCast != nil {
		if err := AssertValueRequired(*obj.DateTimeCast); err != nil {
			return err
		}
	}
	if obj.TimeCast != nil {
		if err := AssertValueRequired(*obj.TimeCast); err != nil {
			return err
		}
	}
	return nil
}

// AssertValueConstraints checks if the values respects the defined constraints
func AssertValueConstraints(obj Value) error {
	if obj.StrCast != nil {
		if err := AssertValueConstraints(*obj.StrCast); err != nil {
			return err
		}
	}
	if obj.NumCast != nil {
		if err := AssertValueConstraints(*obj.NumCast); err != nil {
			return err
		}
	}
	if obj.HexCast != nil {
		if err := AssertValueConstraints(*obj.HexCast); err != nil {
			return err
		}
	}
	if obj.BoolCast != nil {
		if err := AssertValueConstraints(*obj.BoolCast); err != nil {
			return err
		}
	}
	if obj.DateTimeCast != nil {
		if err := AssertValueConstraints(*obj.DateTimeCast); err != nil {
			return err
		}
	}
	if obj.TimeCast != nil {
		if err := AssertValueConstraints(*obj.TimeCast); err != nil {
			return err
		}
	}
	return nil
}
