// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"errors"

	"github.com/FriedJannik/aas-go-sdk/jsonization"
	"github.com/FriedJannik/aas-go-sdk/types"
	"github.com/FriedJannik/aas-go-sdk/verification"
	jsoniter "github.com/json-iterator/go"
)

type InfrastructureDescriptor struct {
	Description []types.ILangStringTextType `json:"description,omitempty"`

	DisplayName []types.ILangStringNameType `json:"displayName,omitempty"`

	Administration types.IAdministrativeInformation `json:"administration,omitempty"`

	Endpoints []Endpoint `json:"endpoints,omitempty"`

	GlobalAssetId string `json:"globalAssetId,omitempty" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	IdShort string `json:"idShort,omitempty" validate:"regexp=^[a-zA-Z][a-zA-Z0-9_-]*[a-zA-Z0-9_]+$"`

	Id string `json:"id" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	Company string `json:"company,omitempty" validate:"regexp=^[A-Za-z0-9]*$"`
}

// AssertInfrastructureDescriptorRequired checks if the required fields are not zero-ed
func AssertInfrastructureDescriptorRequired(obj InfrastructureDescriptor) error {
	elements := map[string]any{
		"id": obj.Id,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}
	for _, el := range obj.Endpoints {
		if err := AssertEndpointRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertInfrastructureDescriptorConstraints checks if the values respects the defined constraints
func AssertInfrastructureDescriptorConstraints(obj InfrastructureDescriptor) error {
	for _, el := range obj.Endpoints {
		if err := AssertEndpointConstraints(el); err != nil {
			return err
		}
	}
	return nil
}

func (obj InfrastructureDescriptor) ToJsonable() (map[string]any, error) {
	// Marshal every AAS GO SDK Type
	ret := make(map[string]any)
	// Description
	var descriptions []map[string]any
	for _, desc := range obj.Description {
		desc, err := jsonization.ToJsonable(desc)
		if err != nil {
			return nil, err
		}
		descriptions = append(descriptions, desc)
	}

	// Display Name
	var displayNames []map[string]any
	for _, dn := range obj.DisplayName {
		dn, err := jsonization.ToJsonable(dn)
		if err != nil {
			return nil, err
		}
		displayNames = append(displayNames, dn)
	}

	// Administration
	var administration map[string]any
	if obj.Administration != nil {
		var err error
		administration, err = jsonization.ToJsonable(obj.Administration)
		if err != nil {
			return nil, err
		}
	}

	if len(descriptions) > 0 {
		ret["description"] = descriptions
	}
	if len(displayNames) > 0 {
		ret["displayName"] = displayNames
	}
	if administration != nil {
		ret["administration"] = administration
	}
	if len(obj.Endpoints) > 0 {
		ret["endpoints"] = obj.Endpoints
	}
	if obj.IdShort != "" {
		ret["idShort"] = obj.IdShort
	}
	if obj.Id != "" {
		ret["id"] = obj.Id
	}
	if obj.Company != "" {
		ret["company"] = obj.Company
	}
	return ret, nil
}

// UnmarshalJSON implements custom unmarshaling for SubmodelDescriptor
// It handles the FromJsonable Unmarshalling of the aas-go-sdk types
func (obj *InfrastructureDescriptor) UnmarshalJSON(data []byte) error {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var jsonable map[string]any
	if err := json.Unmarshal(data, &jsonable); err != nil {
		return err
	}

	// Check for unknown fields
	allowedFields := map[string]bool{
		"administration": true,
		"endpoints":      true,
		"idShort":        true,
		"id":             true,
		"company":        true,
		"description":    true,
		"displayName":    true,
		"extensions":     true,
	}
	for key := range jsonable {
		if !allowedFields[key] {
			return errors.New("unknown field: " + key)
		}
	}

	// Description
	if descs, ok := jsonable["description"].([]any); ok {
		for _, desc := range descs {
			descMap, ok := desc.(map[string]any)
			if !ok {
				return errors.New("InfrastructureDescriptor: description is not a map")
			}
			var langString types.ILangStringTextType
			langString, err := jsonization.LangStringTextTypeFromJsonable(descMap)
			if err != nil {
				return err
			}
			obj.Description = append(obj.Description, langString)
		}
	}

	// Display Name
	if dns, ok := jsonable["displayName"].([]any); ok {
		for _, dn := range dns {
			dnMap, ok := dn.(map[string]any)
			if !ok {
				return errors.New("InfrastructureDescriptor: displayName is not a map")
			}
			var langString types.ILangStringNameType
			langString, err := jsonization.LangStringNameTypeFromJsonable(dnMap)
			if err != nil {
				return err
			}
			obj.DisplayName = append(obj.DisplayName, langString)
		}
	}

	// Endpoints
	if eps, ok := jsonable["endpoints"].([]any); ok {
		for _, ep := range eps {
			epMap, ok := ep.(map[string]any)
			if !ok {
				return errors.New("InfrastructureDescriptor: endpoint is not a map")
			}
			var endpoint Endpoint
			endpointBytes, err := json.Marshal(epMap)
			if err != nil {
				return err
			}
			if err := json.Unmarshal(endpointBytes, &endpoint); err != nil {
				return err
			}
			obj.Endpoints = append(obj.Endpoints, endpoint)
		}
	}

	// Administration
	if admin, ok := jsonable["administration"].(map[string]any); ok {
		var administration types.IAdministrativeInformation
		administration, err := jsonization.AdministrativeInformationFromJsonable(admin)
		if err != nil {
			return err
		}
		obj.Administration = administration
	}

	// Handle other simple fields
	if idShort, ok := jsonable["idShort"].(string); ok {
		obj.IdShort = idShort
	}
	if id, ok := jsonable["id"].(string); ok {
		obj.Id = id
	}
	if company, ok := jsonable["company"].(string); ok {
		obj.Company = company
	}

	// Verify Description
	var validationErrors []string
	for _, el := range obj.Description {
		verification.Verify(el, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})

		if len(validationErrors) > 0 {
			return errors.New("InfrastructureDescriptor: Description verification failed: " + validationErrors[0])
		}
	}

	// Verify DisplayName
	validationErrors = []string{}
	for _, el := range obj.DisplayName {
		verification.Verify(el, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})

		if len(validationErrors) > 0 {
			return errors.New("InfrastructureDescriptor: DisplayName verification failed: " + validationErrors[0])
		}
	}

	// Administration
	validationErrors = []string{}
	if obj.Administration != nil {
		verification.Verify(obj.Administration, func(verErr *verification.VerificationError) bool {
			validationErrors = append(validationErrors, verErr.Error())
			return false // Continue collecting all errors
		})
		if len(validationErrors) > 0 {
			return errors.New("InfrastructureDescriptor: Administration verification failed: " + validationErrors[0])
		}
	}

	return nil
}
