per_listener_settings true
persistence false
listener 1883
allow_anonymous true
listener 1884
allow_anonymous false
password_file /tmp/passwords
listener 8883
allow_anonymous true
cafile /mosquitto/config/mqtt-ca.pem
certfile /mosquitto/config/mqtt-server.pem
keyfile /mosquitto/config/mqtt-server-key.pem
require_certificate true
