// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Discovery Service Specification
 *
 * The entire Full Profile of the Discovery Service Specification as part of the [Specification of the Asset Administration Shell - Part 2: API](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) 2025
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */

package api

import (
	"context"
	"encoding/json"
	"log"
	"net/http"
	"strings"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	persistencepostgresql "github.com/eclipse-basyx/basyx-go-components/internal/discoveryservice/persistence"
)

const (
	componentName = "DISC"
)

// AssetAdministrationShellBasicDiscoveryAPIAPIService is a service that implements the logic for the AssetAdministrationShellBasicDiscoveryAPIAPIServicer
// This service should implement the business logic for every endpoint for the AssetAdministrationShellBasicDiscoveryAPIAPI API.
// Include any external packages or services that will be required by this service.
type AssetAdministrationShellBasicDiscoveryAPIAPIService struct {
	discoveryBackend persistencepostgresql.PostgreSQLDiscoveryDatabase
}

// NewAssetAdministrationShellBasicDiscoveryAPIAPIService creates a default api service
func NewAssetAdministrationShellBasicDiscoveryAPIAPIService(databaseBackend persistencepostgresql.PostgreSQLDiscoveryDatabase) *AssetAdministrationShellBasicDiscoveryAPIAPIService {
	return &AssetAdministrationShellBasicDiscoveryAPIAPIService{
		discoveryBackend: databaseBackend,
	}
}

// GetAllAssetAdministrationShellIdsByAssetLink - Returns a list of Asset Administration Shell IDs linked to specific asset identifiers or the global asset ID
// Deprecated
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) GetAllAssetAdministrationShellIdsByAssetLink(ctx context.Context, assetIds []string, limit int32, cursor string) (model.ImplResponse, error) {
	links := make([]model.AssetLink, 0, len(assetIds))
	for idx, enc := range assetIds {
		if strings.TrimSpace(enc) == "" {
			continue
		}
		dec, err := common.DecodeString(enc)
		if err != nil {
			log.Printf("🧭 [%s] Error GetAllAssetAdministrationShellIdsByAssetLink: decode assetIds[%d]=%q failed: %v", componentName, idx, enc, err)
			return common.NewErrorResponse(
				err, http.StatusBadRequest, componentName, "GetAllAssetAdministrationShellIdsByAssetLink", "assetIds",
			), nil
		}
		var al model.AssetLink
		if err := json.Unmarshal([]byte(dec), &al); err != nil {
			log.Printf("🧭 [%s] Error GetAllAssetAdministrationShellIdsByAssetLink: unmarshal assetIds[%d] decoded=%q failed: %v", componentName, idx, dec, err)
			return common.NewErrorResponse(
				err, http.StatusBadRequest, componentName, "GetAllAssetAdministrationShellIdsByAssetLink", "assetIds",
			), nil
		}
		links = append(links, al)
	}

	return s.SearchAllAssetAdministrationShellIdsByAssetLink(ctx, limit, cursor, links)
}

// SearchAllAssetAdministrationShellIdsByAssetLink - Returns a list of Asset Administration Shell IDs linked to specific asset identifiers or the global asset ID
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) SearchAllAssetAdministrationShellIdsByAssetLink(
	ctx context.Context,
	limit int32,
	cursor string,
	assetLink []model.AssetLink,
) (model.ImplResponse, error) {
	// Decode the incoming cursor only if it’s non-empty; empty means "start from the beginning".
	var internalCursor string
	if strings.TrimSpace(cursor) != "" {
		dec, decErr := common.DecodeString(cursor)
		if decErr != nil {
			log.Printf("🧭 [%s] Error SearchAllAssetAdministrationShellIdsByAssetLink: decode cursor=%q limit=%d links=%d failed: %v", componentName, cursor, limit, len(assetLink), decErr)
			return common.NewErrorResponse(
				decErr, http.StatusBadRequest, componentName, "SearchAllAssetAdministrationShellIdsByAssetLink", "BadCursor",
			), nil
		}
		internalCursor = dec
	}

	ids, nextCursor, err := s.discoveryBackend.SearchAASIDsByAssetLinks(ctx, assetLink, limit, internalCursor)
	if err != nil {
		log.Printf("🧭 [%s] Error SearchAllAssetAdministrationShellIdsByAssetLink: backend search failed (limit=%d cursor=%q links=%d): %v", componentName, limit, internalCursor, len(assetLink), err)
		return common.NewErrorResponse(
			err, http.StatusInternalServerError, componentName, "SearchAllAssetAdministrationShellIdsByAssetLink", "InternalServerError",
		), err
	}

	// Build paging metadata with omitempty behavior: only set cursor when there's a next page.
	pm := model.PagedResultPagingMetadata{}
	if nextCursor != "" {
		pm.Cursor = common.EncodeString(nextCursor)
	}

	res := model.GetAllAssetAdministrationShellIdsByAssetLink200Response{
		PagingMetadata: pm,
		Result:         ids,
	}
	return model.Response(http.StatusOK, res), nil
}

// GetAllAssetLinksByID - Returns a list of specific asset identifiers based on an Asset Administration Shell ID to edit discoverable content.
// The global asset ID is returned as specific asset ID with "name" equal to "globalAssetId" (see Constraint AASd-116).
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) GetAllAssetLinksByID(
	ctx context.Context,
	aasIdentifier string,
) (model.ImplResponse, error) {
	decoded, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		log.Printf("🧭 [%s] Error GetAllAssetLinksById: decode aasIdentifier=%q failed: %v", componentName, aasIdentifier, decodeErr)
		return common.NewErrorResponse(
			decodeErr, http.StatusBadRequest, componentName, "GetAllAssetLinksById", "BadRequest-Decode",
		), nil
	}

	links, err := s.discoveryBackend.GetAllAssetLinks(ctx, string(decoded))
	if err != nil {
		switch {
		case common.IsErrNotFound(err):
			log.Printf("🧭 [%s] Error GetAllAssetLinksById: not found (aasId=%q): %v", componentName, string(decoded), err)
			return common.NewErrorResponse(
				err, http.StatusNotFound, componentName, "GetAllAssetLinksById", "NotFound",
			), nil
		case common.IsErrBadRequest(err):
			log.Printf("🧭 [%s] Error GetAllAssetLinksById: bad request (aasId=%q): %v", componentName, string(decoded), err)
			return common.NewErrorResponse(
				err, http.StatusBadRequest, componentName, "GetAllAssetLinksById", "BadRequest",
			), nil
		default:
			log.Printf("🧭 [%s] Error GetAllAssetLinksById: internal (aasId=%q): %v", componentName, string(decoded), err)
			return common.NewErrorResponse(
				err, http.StatusInternalServerError, componentName, "GetAllAssetLinksById", "Unhandled",
			), err
		}
	}

	return model.Response(http.StatusOK, links), nil
}

// PostAllAssetLinksByID - Creates or replaces all asset links associated to the Asset Administration Shell.
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) PostAllAssetLinksByID(
	ctx context.Context,
	aasIdentifier string,
	specificAssetID []model.SpecificAssetID,
) (model.ImplResponse, error) {
	decodeDiscoveryIdentifier, decodeError := common.DecodeString(aasIdentifier)
	if decodeError != nil {
		log.Printf("🧭 [%s] Error PostAllAssetLinksById: decode aasIdentifier=%q failed: %v", componentName, aasIdentifier, decodeError)
		return common.NewErrorResponse(
			decodeError, http.StatusBadRequest, componentName, "PostAllAssetLinksById", "BadRequest-Decode",
		), nil
	}

	err := s.discoveryBackend.CreateAllAssetLinks(ctx, string(decodeDiscoveryIdentifier), specificAssetID)
	if err != nil {
		switch {
		case common.IsErrBadRequest(err):
			log.Printf("🧭 [%s] Error PostAllAssetLinksById: bad request (aasId=%q): %v", componentName, string(decodeDiscoveryIdentifier), err)
			return common.NewErrorResponse(
				err, http.StatusBadRequest, componentName, "PostAllAssetLinksById", "BadRequest",
			), nil
		default:
			log.Printf("🧭 [%s] Error PostAllAssetLinksById: internal (aasId=%q): %v", componentName, string(decodeDiscoveryIdentifier), err)
			return common.NewErrorResponse(
				err, http.StatusInternalServerError, componentName, "PostAllAssetLinksById", "Unhandled",
			), err
		}
	}

	return model.Response(http.StatusCreated, specificAssetID), nil
}

// DeleteAllAssetLinksByID - Deletes specified specific asset identifiers linked to an Asset Administration Shell:
// discovery via these specific asset IDs shall not be supported any longer
func (s *AssetAdministrationShellBasicDiscoveryAPIAPIService) DeleteAllAssetLinksByID(
	ctx context.Context,
	aasIdentifier string,
) (model.ImplResponse, error) {
	decoded, decodeErr := common.DecodeString(aasIdentifier)
	if decodeErr != nil {
		log.Printf("🧭 [%s] Error DeleteAllAssetLinksById: decode aasIdentifier=%q failed: %v", componentName, aasIdentifier, decodeErr)
		return common.NewErrorResponse(
			decodeErr, http.StatusBadRequest, componentName, "DeleteAllAssetLinksById", "BadRequest-Decode",
		), nil
	}

	err := s.discoveryBackend.DeleteAllAssetLinks(ctx, string(decoded))
	if err != nil {
		switch {
		case common.IsErrNotFound(err):
			log.Printf("🧭 [%s] Error DeleteAllAssetLinksById: not found (aasId=%q): %v", componentName, string(decoded), err)
			return common.NewErrorResponse(
				err, http.StatusNotFound, componentName, "DeleteAllAssetLinksById", "NotFound",
			), nil
		default:
			log.Printf("🧭 [%s] Error DeleteAllAssetLinksById: internal (aasId=%q): %v", componentName, string(decoded), err)
			return common.NewErrorResponse(
				err, http.StatusInternalServerError, componentName, "DeleteAllAssetLinksById", "InternalServerError",
			), err
		}
	}

	return model.Response(http.StatusNoContent, nil), nil
}
