// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Discovery Service Specification
 *
 * The entire Full Profile of the Discovery Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) April 2023
 *
 * API version: V3.2.0
 * Contact: info@idtwin.org
 */

package openapi

import (
	"encoding/json"
	"log/slog"
	"net/http"
	"strings"

	"github.com/FriedJannik/aas-go-sdk/jsonization"
	"github.com/FriedJannik/aas-go-sdk/types"
	"github.com/FriedJannik/aas-go-sdk/verification"
	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	"github.com/go-chi/chi/v5"
)

const (
	componentName = "DISC_VAL"
)

// AssetAdministrationShellBasicDiscoveryAPIAPIController binds http requests to an api service and writes the service results to the http response
type AssetAdministrationShellBasicDiscoveryAPIAPIController struct {
	service      AssetAdministrationShellBasicDiscoveryAPIAPIServicer
	errorHandler model.ErrorHandler
}

// AssetAdministrationShellBasicDiscoveryAPIAPIOption for how the controller is set up.
type AssetAdministrationShellBasicDiscoveryAPIAPIOption func(*AssetAdministrationShellBasicDiscoveryAPIAPIController)

// WithAssetAdministrationShellBasicDiscoveryAPIAPIErrorHandler inject ErrorHandler into controller
func WithAssetAdministrationShellBasicDiscoveryAPIAPIErrorHandler(h model.ErrorHandler) AssetAdministrationShellBasicDiscoveryAPIAPIOption {
	return func(c *AssetAdministrationShellBasicDiscoveryAPIAPIController) {
		c.errorHandler = h
	}
}

// NewAssetAdministrationShellBasicDiscoveryAPIAPIController creates a default api controller
func NewAssetAdministrationShellBasicDiscoveryAPIAPIController(s AssetAdministrationShellBasicDiscoveryAPIAPIServicer, opts ...AssetAdministrationShellBasicDiscoveryAPIAPIOption) *AssetAdministrationShellBasicDiscoveryAPIAPIController {
	controller := &AssetAdministrationShellBasicDiscoveryAPIAPIController{
		service:      s,
		errorHandler: model.DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AssetAdministrationShellBasicDiscoveryAPIAPIController
func (c *AssetAdministrationShellBasicDiscoveryAPIAPIController) Routes() Routes {
	return Routes{
		"GetAllAssetAdministrationShellIdsByAssetLink": Route{
			strings.ToUpper("Get"),
			"/lookup/shells",
			c.GetAllAssetAdministrationShellIdsByAssetLink,
		},
		"SearchAllAssetAdministrationShellIdsByAssetLink": Route{
			strings.ToUpper("Post"),
			"/lookup/shellsByAssetLink",
			c.SearchAllAssetAdministrationShellIdsByAssetLink,
		},
		"GetAllAssetLinksById": Route{
			strings.ToUpper("Get"),
			"/lookup/shells/{aasIdentifier}",
			c.GetAllAssetLinksByID,
		},
		"PostAllAssetLinksById": Route{
			strings.ToUpper("Post"),
			"/lookup/shells/{aasIdentifier}",
			c.PostAllAssetLinksByID,
		},
		"DeleteAllAssetLinksById": Route{
			strings.ToUpper("Delete"),
			"/lookup/shells/{aasIdentifier}",
			c.DeleteAllAssetLinksByID,
		},
	}
}

// GetAllAssetAdministrationShellIdsByAssetLink - Returns a list of Asset Administration Shell ids linked to specific Asset identifiers
func (c *AssetAdministrationShellBasicDiscoveryAPIAPIController) GetAllAssetAdministrationShellIdsByAssetLink(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		slog.ErrorContext(r.Context(), "asset link query parameter parsing failed", "error.code", "DISCOVERYAPI-GETALLASSETADMINISTRATIONSHELLIDSBYASSETLINK-PARSEQUERY", "error", err)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Invalid query parameters"),
			http.StatusBadRequest,
			componentName,
			"GetAllAssetAdministrationShellIdsByAssetLink",
			"query",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	var assetIdsParam []string
	if vals, ok := query["assetIds"]; ok {
		for _, v := range vals {
			if v == "" {
				continue
			}
			parts := strings.Split(v, ",")
			for _, p := range parts {
				p = strings.TrimSpace(p)
				if p != "" {
					assetIdsParam = append(assetIdsParam, p)
				}
			}
		}
	}

	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			slog.ErrorContext(r.Context(), "asset link query limit parsing failed", "error.code", "DISCOVERYAPI-GETALLASSETADMINISTRATIONSHELLIDSBYASSETLINK-PARSELIMIT", "error", err, "limit", query.Get("limit"))
			result := common.NewErrorResponse(
				common.NewErrBadRequest("Invalid 'limit' parameter"),
				http.StatusBadRequest,
				componentName,
				"GetAllAssetAdministrationShellIdsByAssetLink",
				"limit",
			)
			EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
		limitParam = param
	}

	var cursorParam string
	if query.Has("cursor") {
		cursorParam = query.Get("cursor")
	}

	result, err := c.service.GetAllAssetAdministrationShellIdsByAssetLink(r.Context(), assetIdsParam, limitParam, cursorParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// SearchAllAssetAdministrationShellIdsByAssetLink - Returns a list of Asset Administration Shell IDs linked to specific asset identifiers or the global asset ID
func (c *AssetAdministrationShellBasicDiscoveryAPIAPIController) SearchAllAssetAdministrationShellIdsByAssetLink(w http.ResponseWriter, r *http.Request) {
	// parse query (limit, cursor)
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		slog.ErrorContext(r.Context(), "asset link search query parameter parsing failed", "error.code", "DISCOVERYAPI-SEARCHALLASSETADMINISTRATIONSHELLIDSBYASSETLINK-PARSEQUERY", "error", err)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Invalid query parameters"),
			http.StatusBadRequest,
			componentName,
			"SearchAllAssetAdministrationShellIdsByAssetLink",
			"query",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			slog.ErrorContext(r.Context(), "asset link search limit parsing failed", "error.code", "DISCOVERYAPI-SEARCHALLASSETADMINISTRATIONSHELLIDSBYASSETLINK-PARSELIMIT", "error", err, "limit", query.Get("limit"))
			result := common.NewErrorResponse(
				common.NewErrBadRequest("Invalid 'limit' parameter"),
				http.StatusBadRequest,
				componentName,
				"SearchAllAssetAdministrationShellIdsByAssetLink",
				"limit",
			)
			EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
		limitParam = param
	}

	var cursorParam string
	if query.Has("cursor") {
		cursorParam = query.Get("cursor")
	}

	// Body: []AssetLink
	var assetLinksParam []model.AssetLink
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&assetLinksParam); err != nil {
		slog.ErrorContext(r.Context(), "Error in SearchAllAssetAdministrationShellIdsByAssetLink: decode request body failed", "error.code", "DISCOVERYAPI-SEARCHALLASSETADMINISTRATIONSHELLIDSBYASSETLINK-DECODEBODY", "error", err, "component", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Incorrect RequestBody - 01"),
			http.StatusBadRequest,
			componentName,
			"SearchAllAssetAdministrationShellIdsByAssetLink",
			"RequestBody",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	// Validate each element
	for index, al := range assetLinksParam {
		if err := model.AssertAssetLinkRequired(al); err != nil {
			slog.ErrorContext(r.Context(), "asset link validation failed", "error.code", "DISCOVERYAPI-SEARCHALLASSETADMINISTRATIONSHELLIDSBYASSETLINK-VALIDATEELEMENT", "element.index", index, "error", err)
			result := common.NewErrorResponse(
				common.NewErrBadRequest("Invalid asset link element"),
				http.StatusBadRequest,
				componentName,
				"SearchAllAssetAdministrationShellIdsByAssetLink",
				"assetLinks",
			)
			EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
	}

	// Service call
	result, err := c.service.SearchAllAssetAdministrationShellIdsByAssetLink(
		r.Context(),
		limitParam,
		cursorParam,
		assetLinksParam,
	)
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}

	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAllAssetLinksByID - Returns a list of specific Asset identifiers based on an Asset Administration Shell id to edit discoverable content
func (c *AssetAdministrationShellBasicDiscoveryAPIAPIController) GetAllAssetLinksByID(w http.ResponseWriter, r *http.Request) {
	aasIdentifierParam := chi.URLParam(r, "aasIdentifier")
	if aasIdentifierParam == "" {
		slog.ErrorContext(r.Context(), "Error in GetAllAssetLinksById: missing path parameter 'aasIdentifier'", "error.code", "DISCOVERYAPI-GETALLASSETLINKSBYID-VALIDATEPATH", "component", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'aasIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"GetAllAssetLinksById",
			"aasIdentifier",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	result, err := c.service.GetAllAssetLinksByID(r.Context(), aasIdentifierParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostAllAssetLinksByID - Creates specific Asset identifiers linked to an Asset Administration Shell to edit discoverable content
func (c *AssetAdministrationShellBasicDiscoveryAPIAPIController) PostAllAssetLinksByID(w http.ResponseWriter, r *http.Request) {
	aasIdentifierParam := chi.URLParam(r, "aasIdentifier")
	if aasIdentifierParam == "" {
		slog.ErrorContext(r.Context(), "Error in PostAllAssetLinksById: missing path parameter 'aasIdentifier'", "error.code", "DISCOVERYAPI-POSTALLASSETLINKSBYID-VALIDATEPATH", "component", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'aasIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"PostAllAssetLinksById",
			"aasIdentifier",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	var specificAssetIDPayload any
	d := json.NewDecoder(r.Body)
	if err := d.Decode(&specificAssetIDPayload); err != nil {
		slog.ErrorContext(r.Context(), "Error in PostAllAssetLinksById: decode request body failed", "error.code", "DISCOVERYAPI-POSTALLASSETLINKSBYID-DECODEBODY", "error", err, "component", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Incorrect RequestBody - 02"),
			http.StatusBadRequest,
			componentName,
			"PostAllAssetLinksById",
			"RequestBody",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	common.NormalizePayloadNullFields(specificAssetIDPayload)

	specificAssetIDItems, ok := specificAssetIDPayload.([]any)
	if !ok {
		slog.ErrorContext(r.Context(), "Error in PostAllAssetLinksById: payload is not an array", "error.code", "DISCOVERYAPI-POSTALLASSETLINKSBYID-EXECUTE", "component", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Incorrect RequestBody - 02"),
			http.StatusBadRequest,
			componentName,
			"PostAllAssetLinksById",
			"RequestBody",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	var interfaceSpecificAssetIds []types.ISpecificAssetID
	for _, rawItem := range specificAssetIDItems {
		item, ok := rawItem.(map[string]any)
		if !ok {
			slog.ErrorContext(r.Context(), "Error in PostAllAssetLinksById: specific asset id entry is not an object", "error.code", "DISCOVERYAPI-POSTALLASSETLINKSBYID-EXECUTE", "component", componentName)
			result := common.NewErrorResponse(
				common.NewErrBadRequest("Invalid specific asset id element"),
				http.StatusBadRequest,
				componentName,
				"PostAllAssetLinksById",
				"specificAssetId",
			)
			EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}

		saID, err := jsonization.SpecificAssetIDFromJsonable(item)
		if err != nil {
			slog.ErrorContext(r.Context(), "Error in PostAllAssetLinksById: failed to parse specific asset id", "error.code", "DISCOVERYAPI-POSTALLASSETLINKSBYID-EXECUTE", "error", err, "component", componentName)
			result := common.NewErrorResponse(
				common.NewErrBadRequest("Invalid specific asset id element"),
				http.StatusBadRequest,
				componentName,
				"PostAllAssetLinksById",
				"specificAssetId",
			)
			EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
		interfaceSpecificAssetIds = append(interfaceSpecificAssetIds, saID)
	}

	verificationMode := model.GetVerificationMode()
	for index, el := range interfaceSpecificAssetIds {
		specificAssetID := el
		if err := model.ValidateWithMode(
			verificationMode,
			"DISC-POSTASSETLINKS-VERIFY",
			func(collector func(*verification.VerificationError) bool) {
				verification.Verify(specificAssetID, collector)
			},
			func(message string) error {
				return common.NewErrBadRequest("Invalid specific asset id element: " + message)
			},
		); err != nil {
			slog.ErrorContext(r.Context(), "specific asset ID validation failed", "error.code", "DISCOVERYAPI-POSTALLASSETLINKSBYID-VALIDATEELEMENT", "element.index", index, "error", err)
			result := common.NewErrorResponse(
				err,
				http.StatusBadRequest,
				componentName,
				"PostAllAssetLinksById",
				"specificAssetId",
			)
			EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
	}

	result, err := c.service.PostAllAssetLinksByID(r.Context(), aasIdentifierParam, interfaceSpecificAssetIds)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteAllAssetLinksByID - Deletes all specific Asset identifiers linked to an Asset Administration Shell to edit discoverable content
func (c *AssetAdministrationShellBasicDiscoveryAPIAPIController) DeleteAllAssetLinksByID(w http.ResponseWriter, r *http.Request) {
	aasIdentifierParam := chi.URLParam(r, "aasIdentifier")
	if aasIdentifierParam == "" {
		slog.ErrorContext(r.Context(), "Error in DeleteAllAssetLinksById: missing path parameter 'aasIdentifier'", "error.code", "DISCOVERYAPI-DELETEALLASSETLINKSBYID-VALIDATEPATH", "component", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'aasIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"DeleteAllAssetLinksById",
			"aasIdentifier",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	result, err := c.service.DeleteAllAssetLinksByID(r.Context(), aasIdentifierParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
