// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Discovery Service Specification
 *
 * The entire Full Profile of the Discovery Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) April 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

package registryofregistriesapi

import (
	"encoding/json"
	"log"
	"net/http"
	"strings"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	"github.com/go-chi/chi/v5"
)

const (
	componentName = "DISC_VAL"
)

// AssetAdministrationShellRegistryOfRegistriesAPIAPIController binds http requests to an api service and writes the service results to the http response
type AssetAdministrationShellRegistryOfRegistriesAPIAPIController struct {
	service      AssetAdministrationShellRegistryOfRegistriesAPIAPIServicer
	errorHandler model.ErrorHandler
}

// AssetAdministrationShellRegistryOfRegistriesAPIAPIOption for how the controller is set up.
type AssetAdministrationShellRegistryOfRegistriesAPIAPIOption func(*AssetAdministrationShellRegistryOfRegistriesAPIAPIController)

// WithAssetAdministrationShellRegistryOfRegistriesAPIAPIErrorHandler inject ErrorHandler into controller
func WithAssetAdministrationShellRegistryOfRegistriesAPIAPIErrorHandler(h model.ErrorHandler) AssetAdministrationShellRegistryOfRegistriesAPIAPIOption {
	return func(c *AssetAdministrationShellRegistryOfRegistriesAPIAPIController) {
		c.errorHandler = h
	}
}

// NewAssetAdministrationShellRegistryOfRegistriesAPIAPIController creates a default api controller
func NewAssetAdministrationShellRegistryOfRegistriesAPIAPIController(s AssetAdministrationShellRegistryOfRegistriesAPIAPIServicer, opts ...AssetAdministrationShellRegistryOfRegistriesAPIAPIOption) *AssetAdministrationShellRegistryOfRegistriesAPIAPIController {
	controller := &AssetAdministrationShellRegistryOfRegistriesAPIAPIController{
		service:      s,
		errorHandler: model.DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AssetAdministrationShellRegistryOfRegistriesAPIAPIController
func (c *AssetAdministrationShellRegistryOfRegistriesAPIAPIController) Routes() Routes {
	return Routes{
		"GetRegistryByID": Route{
			strings.ToUpper("Get"),
			"/lookup/registries/{registryIdentifier}",
			c.GetRegistryByID,
		},
		"PostRegistryByID": Route{
			strings.ToUpper("Post"),
			"/lookup/registries",
			c.PostRegistry,
		},
	}
}

// GetRegistriesTest - Returns a list of Asset Administration Shell ids linked to specific Asset identifiers
func (c *AssetAdministrationShellRegistryOfRegistriesAPIAPIController) GetRegistryByID(w http.ResponseWriter, r *http.Request) {
	registryIdentifierParam := chi.URLParam(r, "registryIdentifier")
	if registryIdentifierParam == "" {
		log.Printf("Reg [%s] Error in GetRegistryByID: missing path parameter registryIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'registryIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"GetRegistryByID",
			"registryIdentifier",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.GetRegistryDescriptorById(r.Context(), registryIdentifierParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetRegistriesTest - Returns a list of Asset Administration Shell ids linked to specific Asset identifiers
func (c *AssetAdministrationShellRegistryOfRegistriesAPIAPIController) PostRegistry(w http.ResponseWriter, r *http.Request) {
	var registryDescriptorParam model.RegistryDescriptor
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&registryDescriptorParam); err != nil {
		log.Printf("🧩 [%s] Error in PostRegistryDescriptor: decode body: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostRegistryDescriptor",
			"RequestBody",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	if err := model.AssertRegistryDescriptorRequired(registryDescriptorParam); err != nil {
		log.Printf("🧩 [%s] Error in PostRegistryDescriptor: required validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostRegistryDescriptor",
			"RequestBody",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertRegistryDescriptorConstraints(registryDescriptorParam); err != nil {
		log.Printf("🧩 [%s] Error in PostRegistryDescriptor: constraints validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostRegistryDescriptor",
			"RequestBody",
		)
		EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.PostRegistryDescriptor(r.Context(), registryDescriptorParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
