// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Concept Description Repository Service Specification
 *
 * The ConceptDescription Repository Service Specification as part of [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) March 2023
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */

package openapi

import (
	"encoding/base64"
	"net/http"
	"net/url"
	"strings"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
)

func encodeIdentifierForPath(identifier string) string {
	if identifier == "" {
		return ""
	}

	return base64.RawURLEncoding.EncodeToString([]byte(identifier))
}

func requestScheme(r *http.Request) string {
	return common.RequestScheme(r)
}

func requestHost(r *http.Request) string {
	return common.RequestHost(r)
}

func normalizeContextPathForBaseLocation(contextPath string) string {
	trimmed := strings.TrimSpace(contextPath)
	if trimmed == "" || trimmed == "/" {
		return ""
	}

	return "/" + strings.Trim(trimmed, "/")
}

func (c *ConceptDescriptionRepositoryAPIAPIController) buildBaseLocation(r *http.Request) string {
	if externalBaseURL := common.ExternalBaseURLFromContext(r.Context()); externalBaseURL != "" {
		return externalBaseURL
	}

	host := requestHost(r)
	if host == "" {
		return ""
	}

	basePath := normalizeContextPathForBaseLocation(c.contextPath)

	return requestScheme(r) + "://" + host + basePath
}

func (c *ConceptDescriptionRepositoryAPIAPIController) buildConceptDescriptionLocationFromEncodedIdentifier(r *http.Request, encodedConceptDescriptionIdentifier string) string {
	baseLocation := c.buildBaseLocation(r)
	if baseLocation == "" {
		return ""
	}

	escapedConceptDescriptionIdentifier := url.PathEscape(encodedConceptDescriptionIdentifier)

	return baseLocation + "/concept-descriptions/" + escapedConceptDescriptionIdentifier
}

func (c *ConceptDescriptionRepositoryAPIAPIController) buildConceptDescriptionLocationFromRawId(r *http.Request, rawConceptDescriptionID string) string {
	return c.buildConceptDescriptionLocationFromEncodedIdentifier(r, encodeIdentifierForPath(rawConceptDescriptionID))
}

func conceptDescriptionIdentifierFromBody(body interface{}) string {
	bodyMap, ok := body.(map[string]any)
	if !ok {
		return ""
	}

	identifier, ok := bodyMap["id"].(string)
	if !ok {
		return ""
	}

	return identifier
}
