// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Submodel Repository Service Specification
 *
 * The entire Submodel Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

package openapi




type BlobValue struct {

	ContentType string `json:"contentType"`

	Value string `json:"value,omitempty"`
}

// AssertBlobValueRequired checks if the required fields are not zero-ed
func AssertBlobValueRequired(obj BlobValue) error {
	elements := map[string]interface{}{
		"contentType": obj.ContentType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertBlobValueConstraints checks if the values respects the defined constraints
func AssertBlobValueConstraints(obj BlobValue) error {
	return nil
}
