// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Submodel Repository Service Specification
 *
 * The entire Submodel Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

package openapi

type RelationshipElement struct {
	Extensions []Extension `json:"extensions,omitempty"`

	Category string `json:"category,omitempty" validate:"regexp=^([\\\\x09\\\\x0a\\\\x0d\\\\x20-\\\\ud7ff\\\\ue000-\\\\ufffd]|\\\\ud800[\\\\udc00-\\\\udfff]|[\\\\ud801-\\\\udbfe][\\\\udc00-\\\\udfff]|\\\\udbff[\\\\udc00-\\\\udfff])*$"`

	IdShort string `json:"idShort,omitempty"`

	DisplayName []LangStringNameType `json:"displayName,omitempty"`

	Description []LangStringTextType `json:"description,omitempty"`

	ModelType string `json:"modelType" validate:"regexp=^RelationshipElement$"`

	SemanticId Reference `json:"semanticId,omitempty"`

	SupplementalSemanticIds []Reference `json:"supplementalSemanticIds,omitempty"`

	Qualifiers []Qualifier `json:"qualifiers,omitempty"`

	EmbeddedDataSpecifications []EmbeddedDataSpecification `json:"embeddedDataSpecifications,omitempty"`

	First Reference `json:"first"`

	Second Reference `json:"second"`
}

// Getters
func (a RelationshipElement) GetExtensions() []Extension {
	return a.Extensions
}

func (a RelationshipElement) GetIdShort() string {
	return a.IdShort
}

func (a RelationshipElement) GetCategory() string {
	return a.Category
}

func (a RelationshipElement) GetDisplayName() []LangStringNameType {
	return a.DisplayName
}

func (a RelationshipElement) GetDescription() []LangStringTextType {
	return a.Description
}

func (a RelationshipElement) GetModelType() string {
	return a.ModelType
}

func (a RelationshipElement) GetSemanticId() Reference {
	return a.SemanticId
}

func (a RelationshipElement) GetSupplementalSemanticIds() []Reference {
	return a.SupplementalSemanticIds
}

func (a RelationshipElement) GetQualifiers() []Qualifier {
	return a.Qualifiers
}

func (a RelationshipElement) GetEmbeddedDataSpecifications() []EmbeddedDataSpecification {
	return a.EmbeddedDataSpecifications
}

// Setters

func (a *RelationshipElement) SetModelType(v string) {
	a.ModelType = v
}

func (a *RelationshipElement) SetExtensions(v []Extension) {
	a.Extensions = v
}

func (a *RelationshipElement) SetIdShort(v string) {
	a.IdShort = v
}

func (a *RelationshipElement) SetCategory(v string) {
	a.Category = v
}

func (a *RelationshipElement) SetDisplayName(v []LangStringNameType) {
	a.DisplayName = v
}

func (a *RelationshipElement) SetDescription(v []LangStringTextType) {
	a.Description = v
}

func (a *RelationshipElement) SetSemanticId(v Reference) {
	a.SemanticId = v
}

func (a *RelationshipElement) SetSupplementalSemanticIds(v []Reference) {
	a.SupplementalSemanticIds = v
}

func (a *RelationshipElement) SetQualifiers(v []Qualifier) {
	a.Qualifiers = v
}

func (a *RelationshipElement) SetEmbeddedDataSpecifications(v []EmbeddedDataSpecification) {
	a.EmbeddedDataSpecifications = v
}

// AssertRelationshipElementRequired checks if the required fields are not zero-ed
func AssertRelationshipElementRequired(obj RelationshipElement) error {
	elements := map[string]interface{}{
		"modelType": obj.ModelType,
		"first":     obj.First,
		"second":    obj.Second,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Extensions {
		if err := AssertExtensionRequired(el); err != nil {
			return err
		}
	}
	if err := AssertReferableAllOfIdShortRequired(obj.IdShort); err != nil {
		return err
	}
	for _, el := range obj.DisplayName {
		if err := AssertLangStringNameTypeRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Description {
		if err := AssertLangStringTextTypeRequired(el); err != nil {
			return err
		}
	}
	if err := AssertReferenceRequired(obj.SemanticId); err != nil {
		return err
	}
	for _, el := range obj.SupplementalSemanticIds {
		if err := AssertReferenceRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Qualifiers {
		if err := AssertQualifierRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.EmbeddedDataSpecifications {
		if err := AssertEmbeddedDataSpecificationRequired(el); err != nil {
			return err
		}
	}
	if err := AssertReferenceRequired(obj.First); err != nil {
		return err
	}
	if err := AssertReferenceRequired(obj.Second); err != nil {
		return err
	}
	return nil
}

// AssertRelationshipElementConstraints checks if the values respects the defined constraints
func AssertRelationshipElementConstraints(obj RelationshipElement) error {
	for _, el := range obj.Extensions {
		if err := AssertExtensionConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertReferableAllOfIdShortConstraints(obj.IdShort); err != nil {
		return err
	}
	for _, el := range obj.DisplayName {
		if err := AssertLangStringNameTypeConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Description {
		if err := AssertLangStringTextTypeConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertReferenceConstraints(obj.SemanticId); err != nil {
		return err
	}
	for _, el := range obj.SupplementalSemanticIds {
		if err := AssertReferenceConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Qualifiers {
		if err := AssertQualifierConstraints(el); err != nil {
			return err
		}
	}
	for _, el := range obj.EmbeddedDataSpecifications {
		if err := AssertEmbeddedDataSpecificationConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertReferenceConstraints(obj.First); err != nil {
		return err
	}
	if err := AssertReferenceConstraints(obj.Second); err != nil {
		return err
	}
	return nil
}
