// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Submodel Repository Service Specification
 *
 * The entire Submodel Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

package openapi




type Qualifiable1 struct {

	Qualifiers []Qualifier1 `json:"qualifiers,omitempty"`

	ModelType ModelType `json:"modelType"`
}

// AssertQualifiable1Required checks if the required fields are not zero-ed
func AssertQualifiable1Required(obj Qualifiable1) error {
	elements := map[string]interface{}{
		"modelType": obj.ModelType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Qualifiers {
		if err := AssertQualifier1Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertQualifiable1Constraints checks if the values respects the defined constraints
func AssertQualifiable1Constraints(obj Qualifiable1) error {
	for _, el := range obj.Qualifiers {
		if err := AssertQualifier1Constraints(el); err != nil {
			return err
		}
	}
	return nil
}
