// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | Submodel Repository Service Specification
 *
 * The entire Submodel Repository Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * API version: V3.0.3_SSP-001
 * Contact: info@idtwin.org
 */

package openapi




type AnnotatedRelationshipElementValue struct {

	First ReferenceValue `json:"first"`

	Second ReferenceValue `json:"second"`

	Annotations []map[string]interface{} `json:"annotations,omitempty"`
}

// AssertAnnotatedRelationshipElementValueRequired checks if the required fields are not zero-ed
func AssertAnnotatedRelationshipElementValueRequired(obj AnnotatedRelationshipElementValue) error {
	elements := map[string]interface{}{
		"first": obj.First,
		"second": obj.Second,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertReferenceValueRequired(obj.First); err != nil {
		return err
	}
	if err := AssertReferenceValueRequired(obj.Second); err != nil {
		return err
	}
	return nil
}

// AssertAnnotatedRelationshipElementValueConstraints checks if the values respects the defined constraints
func AssertAnnotatedRelationshipElementValueConstraints(obj AnnotatedRelationshipElementValue) error {
	if err := AssertReferenceValueConstraints(obj.First); err != nil {
		return err
	}
	if err := AssertReferenceValueConstraints(obj.Second); err != nil {
		return err
	}
	return nil
}
