// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package registryofinfrastructuresapi

import (
	"encoding/json"
	"log"
	"net/http"
	"strings"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	"github.com/go-chi/chi/v5"
)

const (
	componentName = "AASROR_VAL"
)

// RegistryOfInfrastructuresAPIAPIController binds http requests to an api service and writes the service results to the http response
type RegistryOfInfrastructuresAPIAPIController struct {
	service      RegistryOfInfrastructuresAPIAPIServicer
	errorHandler model.ErrorHandler
}

// RegistryOfInfrastructuresAPIAPIOption for how the controller is set up.
type RegistryOfInfrastructuresAPIAPIOption func(*RegistryOfInfrastructuresAPIAPIController)

// WithRegistryOfInfrastructuresAPIAPIErrorHandler inject ErrorHandler into controller
func WithRegistryOfInfrastructuresAPIAPIErrorHandler(h model.ErrorHandler) RegistryOfInfrastructuresAPIAPIOption {
	return func(c *RegistryOfInfrastructuresAPIAPIController) {
		c.errorHandler = h
	}
}

// NewRegistryOfInfrastructuresAPIAPIController creates a default api controller
func NewRegistryOfInfrastructuresAPIAPIController(s RegistryOfInfrastructuresAPIAPIServicer, opts ...RegistryOfInfrastructuresAPIAPIOption) *RegistryOfInfrastructuresAPIAPIController {
	controller := &RegistryOfInfrastructuresAPIAPIController{
		service:      s,
		errorHandler: model.DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the RegistryOfInfrastructuresAPIAPIController
func (c *RegistryOfInfrastructuresAPIAPIController) Routes() Routes {
	return Routes{
		"GetAllInfrastructureDescriptors": Route{
			strings.ToUpper("Get"),
			"/infrastructure-descriptors",
			c.GetAllInfrastructureDescriptors,
		},
		"PostInfrastructureDescriptor": Route{
			strings.ToUpper("Post"),
			"/infrastructure-descriptors",
			c.PostInfrastructureDescriptor,
		},
		"GetInfrastructureDescriptorById": Route{
			strings.ToUpper("Get"),
			"/infrastructure-descriptors/{infrastructureIdentifier}",
			c.GetInfrastructureDescriptorById,
		},
		"PutInfrastructureDescriptorById": Route{
			strings.ToUpper("Put"),
			"/infrastructure-descriptors/{infrastructureIdentifier}",
			c.PutInfrastructureDescriptorById,
		},
		"DeleteInfrastructureDescriptorById": Route{
			strings.ToUpper("Delete"),
			"/infrastructure-descriptors/{infrastructureIdentifier}",
			c.DeleteInfrastructureDescriptorById,
		},
	}
}

// GetAllInfrastructureDescriptors - Returns all Infrastructure Descriptors
func (c *RegistryOfInfrastructuresAPIAPIController) GetAllInfrastructureDescriptors(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		log.Printf("📍 [%s] Error in GetAllInfrastructureDescriptors: parse query raw=%q: %v", componentName, r.URL.RawQuery, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"GetAllInfrastructureDescriptors",
			"query",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			log.Printf("📍 [%s] Error in GetAllInfrastructureDescriptors: parse limit=%q: %v", componentName, query.Get("limit"), err)
			result := common.NewErrorResponse(
				err,
				http.StatusBadRequest,
				componentName,
				"GetAllInfrastructureDescriptors",
				"limit",
			)
			_ = EncodeJSONResponse(result.Body, &result.Code, w)
			return
		}
		limitParam = param
	}
	var cursorParam string
	if query.Has("cursor") {
		cursorParam = query.Get("cursor")
	}
	var companyParam string
	if query.Has("company") {
		companyParam = query.Get("company")
	}
	var endpointInterfaceParam string
	if query.Has("endpointInterface") {
		endpointInterfaceParam = query.Get("endpointInterface")
	}

	result, err := c.service.GetAllInfrastructureDescriptors(r.Context(), limitParam, cursorParam, companyParam, endpointInterfaceParam)
	if err != nil {
		log.Printf("📍 [%s] Error in GetAllInfrastructureDescriptors: service failure (limit=%d cursor=%q company=%q endpointInterface=%q): %v", componentName, limitParam, cursorParam, companyParam, endpointInterfaceParam, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PostInfrastructureDescriptor - Creates a new Infrastructure Descriptor, i.e. registers a registry
func (c *RegistryOfInfrastructuresAPIAPIController) PostInfrastructureDescriptor(w http.ResponseWriter, r *http.Request) {
	var infrastructureDescriptorParam model.InfrastructureDescriptor
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&infrastructureDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PostInfrastructureDescriptor: decode body: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostInfrastructureDescriptor",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}

	if err := model.AssertInfrastructureDescriptorRequired(infrastructureDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PostInfrastructureDescriptor: required validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostInfrastructureDescriptor",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertInfrastructureDescriptorConstraints(infrastructureDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PostInfrastructureDescriptor: constraints validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PostInfrastructureDescriptor",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.PostInfrastructureDescriptor(r.Context(), infrastructureDescriptorParam)
	if err != nil {
		log.Printf("📍 [%s] Error in PostInfrastructureDescriptor: service failure (bodyId=%q): %v", componentName, infrastructureDescriptorParam.Id, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetInfrastructureDescriptorById - Returns a specific Infrastructure Descriptor
func (c *RegistryOfInfrastructuresAPIAPIController) GetInfrastructureDescriptorById(w http.ResponseWriter, r *http.Request) {

	infrastructureIdentifierParam := chi.URLParam(r, "infrastructureIdentifier")
	if infrastructureIdentifierParam == "" {
		log.Printf("📍 [%s] Error in GetInfrastructureDescriptorById: missing path parameter infrastructureIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'infrastructureIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"GetInfrastructureDescriptorById",
			"infrastructureIdentifier",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.GetInfrastructureDescriptorById(r.Context(), infrastructureIdentifierParam)
	if err != nil {
		log.Printf("📍 [%s] Error in GetInfrastructureDescriptorById: service failure (infrastructureIdentifier=%q): %v", componentName, infrastructureIdentifierParam, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// PutInfrastructureDescriptorById - Creates or updates an existing Infrastructure Descriptor
func (c *RegistryOfInfrastructuresAPIAPIController) PutInfrastructureDescriptorById(w http.ResponseWriter, r *http.Request) {
	infrastructureIdentifierParam := chi.URLParam(r, "infrastructureIdentifier")
	if infrastructureIdentifierParam == "" {
		log.Printf("📍 [%s] Error in PutInfrastructureDescriptorById: missing path parameter infrastructureIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'infrastructureIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"PutInfrastructureDescriptorById",
			"infrastructureIdentifier",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	var infrastructureDescriptorParam model.InfrastructureDescriptor
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&infrastructureDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PutInfrastructureDescriptorById: decode body: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PutInfrastructureDescriptorById",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertInfrastructureDescriptorRequired(infrastructureDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PutInfrastructureDescriptorById: required validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PutInfrastructureDescriptorById",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	if err := model.AssertInfrastructureDescriptorConstraints(infrastructureDescriptorParam); err != nil {
		log.Printf("📍 [%s] Error in PutInfrastructureDescriptorById: constraints validation failed: %v", componentName, err)
		result := common.NewErrorResponse(
			err,
			http.StatusBadRequest,
			componentName,
			"PutInfrastructureDescriptorById",
			"RequestBody",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.PutInfrastructureDescriptorById(r.Context(), infrastructureIdentifierParam, infrastructureDescriptorParam)
	if err != nil {
		log.Printf("📍 [%s] Error in PutInfrastructureDescriptorById: service failure (infrastructureIdentifier=%q bodyId=%q): %v", componentName, infrastructureIdentifierParam, infrastructureDescriptorParam.Id, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteInfrastructureDescriptorById - Deletes a Infrastructure Descriptor, i.e. de-registers a registry
func (c *RegistryOfInfrastructuresAPIAPIController) DeleteInfrastructureDescriptorById(w http.ResponseWriter, r *http.Request) {
	infrastructureIdentifierParam := chi.URLParam(r, "infrastructureIdentifier")
	if infrastructureIdentifierParam == "" {
		log.Printf("📍 [%s] Error in DeleteInfrastructureDescriptorById: missing path parameter infrastructureIdentifier", componentName)
		result := common.NewErrorResponse(
			common.NewErrBadRequest("Missing path parameter 'infrastructureIdentifier'"),
			http.StatusBadRequest,
			componentName,
			"DeleteInfrastructureDescriptorById",
			"infrastructureIdentifier",
		)
		_ = EncodeJSONResponse(result.Body, &result.Code, w)
		return
	}
	result, err := c.service.DeleteInfrastructureDescriptorById(r.Context(), infrastructureIdentifierParam)
	if err != nil {
		log.Printf("📍 [%s] Error in DeleteInfrastructureDescriptorById: service failure (infrastructureIdentifier=%q): %v", componentName, infrastructureIdentifierParam, err)
		c.errorHandler(w, r, err, &result)
		return
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
