const fs = require("fs");
const path = require("path");

const collection = {
  source: "examples/CatenaXample/CatenaXample.postman_collection.json",
  target: "examples/CatenaXample/bruno",
  singleFileTarget: "examples/CatenaXample/CatenaXample.opencollection.yml",
  name: "CatenaXample",
};

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(file, content) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content, "utf8");
}

function prepareTarget(target) {
  const marker = path.join(target, ".generated-by-postman-to-bruno");

  if (fs.existsSync(target)) {
    if (!fs.existsSync(marker)) {
      throw new Error(`${target} exists and is not marked as generated`);
    }
    fs.rmSync(target, { recursive: true, force: true });
  }

  ensureDir(target);
  writeFile(marker, "Generated by scripts/generate_bruno_collections.js\n");
}

function sanitizeName(name) {
  return (
    name
      .normalize("NFKD")
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .replace(/-{2,}/g, "-") || "request"
  );
}

function indent(text, spaces = 2) {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => pad + line)
    .join("\n");
}

function yamlString(value) {
  return JSON.stringify(String(value));
}

function variableMap(postman) {
  return Object.fromEntries((postman.variable || []).map((variable) => [variable.key, variable.value || ""]));
}

function resolveVariables(value, variables) {
  return String(value).replace(/\{\{([^}]+)\}\}/g, (_, key) => variables[key] ?? "");
}

function authType(headers) {
  const authorization = (headers || []).find((header) => header.key.toLowerCase() === "authorization");

  if (!authorization) {
    return "";
  }

  if (authorization.value.includes("{{adminAccessToken}}")) {
    return "admin";
  }

  if (authorization.value.includes("{{userAccessToken}}")) {
    return "user";
  }

  return "";
}

function tokenScript(type, variables) {
  const username = type === "admin" ? variables.adminUsername : variables.regularUsername;
  const password = type === "admin" ? variables.adminPassword : variables.regularPassword;
  const tokenVariable = type === "admin" ? "adminAccessToken" : "userAccessToken";
  const expiresAtVariable = type === "admin" ? "adminAccessTokenExpiresAt" : "userAccessTokenExpiresAt";

  return [
    `const tokenVariable = "${tokenVariable}";`,
    `const expiresAtVariable = "${expiresAtVariable}";`,
    "const nowSeconds = Math.floor(Date.now() / 1000);",
    "",
    "function tokenIsFresh() {",
    "  const expiresAt = Number(bru.getVar(expiresAtVariable) || 0);",
    "  return expiresAt - 30 > nowSeconds;",
    "}",
    "",
    "function formUrlEncode(fields) {",
    "  return Object.entries(fields)",
    "    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)",
    '    .join("&");',
    "}",
    "",
    "async function requestOAuth2Token() {",
    "  if (tokenIsFresh()) {",
    "    return bru.getVar(tokenVariable);",
    "  }",
    "",
    "  const response = await bru.sendRequest({",
    `    url: "${variables.keycloakTokenUrl}",`,
    '    method: "POST",',
    "    headers: {",
    '      "Content-Type": "application/x-www-form-urlencoded",',
    "    },",
    "    data: formUrlEncode({",
    '      grant_type: "password",',
    `      client_id: "${variables.keycloakClientId}",`,
    `      username: "${username}",`,
    `      password: "${password}",`,
    "    }),",
    "  });",
    "",
    "  const status = response.status || response.statusCode || response.code;",
    "  if (status !== 200) {",
    "    throw new Error(`OAuth2 token request failed with status ${status}`);",
    "  }",
    "",
    '  const tokenResponse = typeof response.data === "string" ? JSON.parse(response.data) : response.data;',
    "  bru.setVar(tokenVariable, tokenResponse.access_token);",
    "  bru.setVar(expiresAtVariable, String(nowSeconds + Number(tokenResponse.expires_in || 300)));",
    "",
    "  return tokenResponse.access_token;",
    "}",
    "",
    "const token = await requestOAuth2Token();",
    "req.setHeader(\"Authorization\", `Bearer ${token}`);",
  ].join("\n");
}

function translateTests(events) {
  const lines = (events || [])
    .filter((event) => event.listen === "test")
    .flatMap((event) => event.script?.exec || []);

  if (lines.length === 0) {
    return "";
  }

  let script = lines.join("\n");
  script = script.replace(/pm\.test\(/g, "test(");
  script = script.replace(/pm\.response\.to\.have\.status\(([^)]+)\);/g, "expect(res.status).to.equal($1);");
  script = script.replace(/pm\.expect\(/g, "expect(");
  script = script.replace(/pm\.response\.code/g, "res.status");
  script = script.replace(/pm\.response\.json\(\)/g, "res.body");

  return script;
}

function renderRuntime(beforeRequestScript, testsScript) {
  const scripts = [];

  if (beforeRequestScript) {
    scripts.push(["    - type: before-request", "      code: |-", indent(beforeRequestScript, 8)].join("\n"));
  }

  if (testsScript) {
    scripts.push(["    - type: tests", "      code: |-", indent(testsScript, 8)].join("\n"));
  }

  if (scripts.length === 0) {
    return "";
  }

  return ["runtime:", "  scripts:", ...scripts].join("\n");
}

function renderHeaders(headers, variables) {
  const filtered = (headers || []).filter((header) => header.key.toLowerCase() !== "authorization");

  if (filtered.length === 0) {
    return "";
  }

  return [
    "  headers:",
    ...filtered.flatMap((header) => [
      `    - name: ${yamlString(header.key)}`,
      `      value: ${yamlString(resolveVariables(header.value, variables))}`,
    ]),
  ].join("\n");
}

function renderBody(body, variables) {
  if (!body || body.mode !== "raw") {
    return "";
  }

  return ["  body:", "    type: json", "    data: |-", indent(resolveVariables(body.raw, variables), 6)].join("\n");
}

function renderSingleHeaders(headers, variables, spaces) {
  const filtered = (headers || []).filter((header) => header.key.toLowerCase() !== "authorization");

  if (filtered.length === 0) {
    return [];
  }

  return [
    `${" ".repeat(spaces)}headers:`,
    ...filtered.flatMap((header) => [
      `${" ".repeat(spaces + 2)}- name: ${yamlString(header.key)}`,
      `${" ".repeat(spaces + 4)}value: ${yamlString(resolveVariables(header.value, variables))}`,
    ]),
  ];
}

function renderSingleBody(body, variables, spaces) {
  if (!body || body.mode !== "raw") {
    return [];
  }

  return [
    `${" ".repeat(spaces)}body:`,
    `${" ".repeat(spaces + 2)}type: json`,
    `${" ".repeat(spaces + 2)}data: |-`,
    indent(resolveVariables(body.raw, variables), spaces + 4),
  ];
}

function renderSingleRuntime(beforeRequestScript, testsScript, spaces) {
  const scripts = [];

  if (beforeRequestScript) {
    scripts.push([
      `${" ".repeat(spaces + 2)}- type: before-request`,
      `${" ".repeat(spaces + 4)}code: |-`,
      indent(beforeRequestScript, spaces + 6),
    ]);
  }

  if (testsScript) {
    scripts.push([
      `${" ".repeat(spaces + 2)}- type: tests`,
      `${" ".repeat(spaces + 4)}code: |-`,
      indent(testsScript, spaces + 6),
    ]);
  }

  if (scripts.length === 0) {
    return [];
  }

  return [`${" ".repeat(spaces)}runtime:`, `${" ".repeat(spaces + 2)}scripts:`, ...scripts.flat()];
}

function renderSingleRequest(item, seq, variables, spaces) {
  const request = item.request;
  const headers = request.header || [];
  const requestAuthType = authType(headers);
  const beforeRequestScript = requestAuthType ? tokenScript(requestAuthType, variables) : "";
  const testsScript = translateTests(item.event);

  return [
    `${" ".repeat(spaces)}- info:`,
    `${" ".repeat(spaces + 4)}name: ${yamlString(item.name)}`,
    `${" ".repeat(spaces + 4)}type: http`,
    `${" ".repeat(spaces + 4)}seq: ${seq}`,
    `${" ".repeat(spaces + 2)}http:`,
    `${" ".repeat(spaces + 4)}method: ${request.method.toUpperCase()}`,
    `${" ".repeat(spaces + 4)}url: ${yamlString(resolveVariables(request.url.raw, variables))}`,
    ...renderSingleHeaders(headers, variables, spaces + 4),
    ...renderSingleBody(request.body, variables, spaces + 4),
    `${" ".repeat(spaces + 4)}auth:`,
    `${" ".repeat(spaces + 6)}type: none`,
    ...renderSingleRuntime(beforeRequestScript, testsScript, spaces + 2),
    `${" ".repeat(spaces + 2)}settings:`,
    `${" ".repeat(spaces + 4)}encodeUrl: true`,
    `${" ".repeat(spaces + 4)}timeout: 0`,
    `${" ".repeat(spaces + 4)}followRedirects: true`,
    `${" ".repeat(spaces + 4)}maxRedirects: 5`,
  ];
}

function renderRequest(item, seq, variables) {
  const request = item.request;
  const headers = request.header || [];
  const requestAuthType = authType(headers);
  const body = renderBody(request.body, variables);
  const renderedHeaders = renderHeaders(headers, variables);
  const beforeRequestScript = requestAuthType ? tokenScript(requestAuthType, variables) : "";
  const testsScript = translateTests(item.event);
  const runtime = renderRuntime(beforeRequestScript, testsScript);
  const parts = [
    "info:",
    `  name: ${yamlString(item.name)}`,
    "  type: http",
    `  seq: ${seq}`,
    "",
    "http:",
    `  method: ${request.method.toUpperCase()}`,
    `  url: ${yamlString(resolveVariables(request.url.raw, variables))}`,
  ];

  if (renderedHeaders) {
    parts.push(renderedHeaders);
  }

  if (body) {
    parts.push(body);
  }

  parts.push("  auth:", "    type: none");

  if (runtime) {
    parts.push("", runtime);
  }

  parts.push("", "settings:", "  encodeUrl: true", "  timeout: 0", "  followRedirects: true", "  maxRedirects: 5");

  return parts.join("\n") + "\n";
}

function renderFolder(folder, seq) {
  return ["info:", `  name: ${yamlString(folder.name)}`, "  type: folder", `  seq: ${seq}`, ""].join("\n");
}

function writeCollection(config) {
  const postman = JSON.parse(fs.readFileSync(config.source, "utf8"));
  const variables = variableMap(postman);
  prepareTarget(config.target);

  writeFile(
    path.join(config.target, "opencollection.yml"),
    ["info:", `  name: ${yamlString(config.name)}`, "  type: collection", '  version: "1"', ""].join("\n"),
  );
  writeFile(path.join(config.target, ".gitignore"), ["node_modules/", ".bruno/", "*.env", "environments/*.yml", ""].join("\n"));

  let folderSeq = 1;
  for (const folder of postman.item) {
    const folderDir = path.join(config.target, `${String(folderSeq).padStart(2, "0")}-${sanitizeName(folder.name)}`);
    ensureDir(folderDir);
    writeFile(path.join(folderDir, "folder.yml"), renderFolder(folder, folderSeq));

    let requestSeq = 1;
    for (const item of folder.item || []) {
      const fileName = `${String(requestSeq).padStart(2, "0")}-${sanitizeName(item.name)}.yml`;
      writeFile(path.join(folderDir, fileName), renderRequest(item, requestSeq, variables));
      requestSeq++;
    }

    folderSeq++;
  }
}

function renderSingleFolder(folder, seq, variables) {
  const lines = [
    "  - info:",
    `      name: ${yamlString(folder.name)}`,
    "      type: folder",
    `      seq: ${seq}`,
    "    items:",
  ];

  let requestSeq = 1;
  for (const item of folder.item || []) {
    lines.push(...renderSingleRequest(item, requestSeq, variables, 6));
    requestSeq++;
  }

  return lines;
}

function writeSingleFile(config) {
  const postman = JSON.parse(fs.readFileSync(config.source, "utf8"));
  const variables = variableMap(postman);
  const lines = [
    "info:",
    `  name: ${yamlString(config.name)}`,
    "  type: collection",
    '  version: "1"',
    "items:",
  ];

  let folderSeq = 1;
  for (const folder of postman.item) {
    lines.push(...renderSingleFolder(folder, folderSeq, variables));
    folderSeq++;
  }

  writeFile(config.singleFileTarget, lines.join("\n") + "\n");
}

writeCollection(collection);
writeSingleFile(collection);
