/*******************************************************************************
* Copyright (C) 2026 the Eclipse BaSyx Authors and Fraunhofer IESE
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
* LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* SPDX-License-Identifier: MIT
******************************************************************************/
// Author: Martin Stemmer ( Fraunhofer IESE )

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
/*
 * DotAAS Part 2 | HTTP/REST | Submodel Registry Service Specification
 *
 * The Full Profile of the Submodel Registry Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](https://industrialdigitaltwin.org/en/content-hub/aasspecifications).   Copyright: Industrial Digital Twin Association (IDTA) 2025
 *
 * API version: V3.1.1_SSP-001
 * Contact: info@idtwin.org
 */
package openapi

import (
	"context"
	"errors"
	"net/http"

	"github.com/eclipse-basyx/basyx-go-components/internal/common/model"
	smregistrypostgresql "github.com/eclipse-basyx/basyx-go-components/internal/smregistry/persistence"
)

// SubmodelRegistryAPIAPIService is a service that implements the logic for the SubmodelRegistryAPIAPIServicer
// This service should implement the business logic for every endpoint for the SubmodelRegistryAPIAPI API.
// Include any external packages or services that will be required by this service.
type SubmodelRegistryAPIAPIService struct {
	smRegistryBackend smregistrypostgresql.PostgreSQLSMDatabase
}

// NewSubmodelRegistryAPIAPIService creates a default api service
func NewSubmodelRegistryAPIAPIService(databaseBackend smregistrypostgresql.PostgreSQLSMDatabase) *SubmodelRegistryAPIAPIService {
	return &SubmodelRegistryAPIAPIService{
		smRegistryBackend: databaseBackend,
	}
}

// GetAllSubmodelDescriptors - Returns all Submodel Descriptors
func (s *SubmodelRegistryAPIAPIService) GetAllSubmodelDescriptors(ctx context.Context, limit int32, cursor string) (model.ImplResponse, error) {
	// TODO - update GetAllSubmodelDescriptors with the required logic for this service method.
	// Add api_submodel_registry_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetSubmodelDescriptorsResult{}) or use other options such as http.Ok ...
	// return Response(200, GetSubmodelDescriptorsResult{}), nil

	// TODO: Uncomment the next line to return response Response(400, Result{}) or use other options such as http.Ok ...
	// return Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response Response(403, Result{}) or use other options such as http.Ok ...
	// return Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response Response(404, Result{}) or use other options such as http.Ok ...
	// return Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response Response(500, Result{}) or use other options such as http.Ok ...
	// return Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response Response(0, Result{}) or use other options such as http.Ok ...
	// return Response(0, Result{}), nil

	return model.Response(http.StatusNotImplemented, nil), errors.New("GetAllSubmodelDescriptors method not implemented")
}

// PostSubmodelDescriptor - Creates a new Submodel Descriptor, i.e. registers a submodel
func (s *SubmodelRegistryAPIAPIService) PostSubmodelDescriptor(ctx context.Context, submodelDescriptor model.SubmodelDescriptor) (model.ImplResponse, error) {
	// TODO - update PostSubmodelDescriptor with the required logic for this service method.
	// Add api_submodel_registry_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, SubmodelDescriptor{}) or use other options such as http.Ok ...
	// return Response(201, SubmodelDescriptor{}), nil

	// TODO: Uncomment the next line to return response Response(400, Result{}) or use other options such as http.Ok ...
	// return Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response Response(403, Result{}) or use other options such as http.Ok ...
	// return Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response Response(409, Result{}) or use other options such as http.Ok ...
	// return Response(409, Result{}), nil

	// TODO: Uncomment the next line to return response Response(0, Result{}) or use other options such as http.Ok ...
	// return Response(0, Result{}), nil

	return model.Response(http.StatusNotImplemented, nil), errors.New("PostSubmodevlDescriptor method not implemented")
}

// GetSubmodelDescriptorById - Returns a specific Submodel Descriptor
func (s *SubmodelRegistryAPIAPIService) GetSubmodelDescriptorById(ctx context.Context, submodelIdentifier string) (model.ImplResponse, error) {
	// TODO - update GetSubmodelDescriptorById with the required logic for this service method.
	// Add api_submodel_registry_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SubmodelDescriptor{}) or use other options such as http.Ok ...
	// return Response(200, SubmodelDescriptor{}), nil

	// TODO: Uncomment the next line to return response Response(400, Result{}) or use other options such as http.Ok ...
	// return Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response Response(403, Result{}) or use other options such as http.Ok ...
	// return Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response Response(404, Result{}) or use other options such as http.Ok ...
	// return Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response Response(500, Result{}) or use other options such as http.Ok ...
	// return Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response Response(0, Result{}) or use other options such as http.Ok ...
	// return Response(0, Result{}), nil

	return model.Response(http.StatusNotImplemented, nil), errors.New("GetSubmodelDescriptorById method not implemented")
}

// PutSubmodelDescriptorById - Creates or updates an existing Submodel Descriptor
func (s *SubmodelRegistryAPIAPIService) PutSubmodelDescriptorById(ctx context.Context, submodelIdentifier string, submodelDescriptor model.SubmodelDescriptor) (model.ImplResponse, error) {
	// TODO - update PutSubmodelDescriptorById with the required logic for this service method.
	// Add api_submodel_registry_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, SubmodelDescriptor{}) or use other options such as http.Ok ...
	// return Response(201, SubmodelDescriptor{}), nil

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Result{}) or use other options such as http.Ok ...
	// return Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response Response(403, Result{}) or use other options such as http.Ok ...
	// return Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response Response(500, Result{}) or use other options such as http.Ok ...
	// return Response(500, Result{}), nil

	// TODO: Uncomment the next line to return response Response(0, Result{}) or use other options such as http.Ok ...
	// return Response(0, Result{}), nil

	return model.Response(http.StatusNotImplemented, nil), errors.New("PutSubmodelDescriptorById method not implemented")
}

// DeleteSubmodelDescriptorById - Deletes a Submodel Descriptor, i.e. de-registers a submodel
func (s *SubmodelRegistryAPIAPIService) DeleteSubmodelDescriptorById(ctx context.Context, submodelIdentifier string) (model.ImplResponse, error) {
	// TODO - update DeleteSubmodelDescriptorById with the required logic for this service method.
	// Add api_submodel_registry_api_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Result{}) or use other options such as http.Ok ...
	// return Response(400, Result{}), nil

	// TODO: Uncomment the next line to return response Response(403, Result{}) or use other options such as http.Ok ...
	// return Response(403, Result{}), nil

	// TODO: Uncomment the next line to return response Response(404, Result{}) or use other options such as http.Ok ...
	// return Response(404, Result{}), nil

	// TODO: Uncomment the next line to return response Response(500, Result{}) or use other options such as http.Ok ...
	// return Response(500, Result{}), nil

	return model.Response(http.StatusNotImplemented, nil), errors.New("DeleteSubmodelDescriptorById method not implemented")
}
