/*******************************************************************************
* Copyright (C) 2026 the Eclipse BaSyx Authors and Fraunhofer IESE
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal in the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject to
* the following conditions:
*
* The above copyright notice and this permission notice shall be
* included in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
* LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* SPDX-License-Identifier: MIT
******************************************************************************/
// Author: Jannik Fried (Fraunhofer IESE)

package persistence

import (
	"context"
	"errors"

	"github.com/FriedJannik/aas-go-sdk/jsonization"
	"github.com/FriedJannik/aas-go-sdk/types"
	"github.com/eclipse-basyx/basyx-go-components/internal/common"
	"github.com/eclipse-basyx/basyx-go-components/internal/common/jws"
	gen "github.com/eclipse-basyx/basyx-go-components/internal/common/model"
)

// GetSignedSubmodel returns a compact JWS for the requested Submodel in full
// representation.
//
// The method loads the Submodel through the normal repository read path with
// level "deep", so visibility and ABAC rules from ctx are preserved. The
// Submodel is converted to its JSON representation, canonicalized for stable
// payload bytes, and signed with RS256. The compact JWS contains the BaSyx/IDTA
// protected headers generated by the common JWS signer, including "typ",
// "sigT", "sid", and optionally "x5c" when SetJWSCertificateChain was
// configured.
//
// Parameters:
//   - ctx: Request context carrying configuration, security, and ABAC data.
//   - submodelID: Identifier of the Submodel to fetch and sign.
//
// Returns:
//   - string: Compact serialized JWS containing the canonical full Submodel
//     JSON payload.
//   - error: Error when signing is not configured, the Submodel cannot be
//     loaded, JSON conversion or canonicalization fails, or JWS signing fails.
func (s *SubmodelDatabase) GetSignedSubmodel(ctx context.Context, submodelID string) (string, error) {
	if s.privateKey == nil {
		return "", errors.New("JWS signing not configured: private key not loaded")
	}

	submodel, err := s.GetSubmodelByID(ctx, submodelID, "deep", false)
	if err != nil {
		return "", err
	}

	var payload []byte

	payload, err = getNormalPayload(submodel)
	if err != nil {
		return "", err
	}

	return jws.SignPayloadWithOptions(s.privateKey, payload, s.signingOptions)
}

// GetSignedSubmodelValueOnly returns a compact JWS for the requested Submodel
// in value-only representation.
//
// The method loads the Submodel through the normal repository read path with
// level "deep", so visibility and ABAC rules from ctx are preserved. It then
// converts the model to the AAS value-only representation, canonicalizes the
// resulting JSON for stable payload bytes, and signs it with RS256. The compact
// JWS contains the BaSyx/IDTA protected headers generated by the common JWS
// signer, including "typ", "sigT", "sid", and optionally "x5c" when
// SetJWSCertificateChain was configured.
//
// Parameters:
//   - ctx: Request context carrying configuration, security, and ABAC data.
//   - submodelID: Identifier of the Submodel to fetch and sign.
//
// Returns:
//   - string: Compact serialized JWS containing the canonical value-only
//     Submodel JSON payload.
//   - error: Error when signing is not configured, the Submodel cannot be
//     loaded, value-only conversion or canonicalization fails, or JWS signing
//     fails.
func (s *SubmodelDatabase) GetSignedSubmodelValueOnly(ctx context.Context, submodelID string) (string, error) {
	if s.privateKey == nil {
		return "", errors.New("JWS signing not configured: private key not loaded")
	}

	submodel, err := s.GetSubmodelByID(ctx, submodelID, "deep", false)
	if err != nil {
		return "", err
	}

	payload, err := getValueOnlyPayload(submodel)
	if err != nil {
		return "", err
	}

	return jws.SignPayloadWithOptions(s.privateKey, payload, s.signingOptions)
}

func getNormalPayload(submodel types.ISubmodel) ([]byte, error) {
	jsonSubmodel, convertErr := jsonization.ToJsonable(submodel)
	if convertErr != nil {
		return nil, convertErr
	}
	return common.CanonicalJSON(jsonSubmodel)
}

func getValueOnlyPayload(submodel types.ISubmodel) ([]byte, error) {
	valueOnlySubmodel, conversionErr := gen.SubmodelToValueOnly(submodel)
	if conversionErr != nil {
		return nil, conversionErr
	}
	return common.CanonicalJSON(valueOnlySubmodel)
}
