events {}

http {
  server {
    listen 4444;

    location = /oauth2/auth {
      proxy_set_header Host $http_host;
      proxy_pass http://hydra:4444/oauth2/auth?$query_string&audience=basyx-api;
    }

    location / {
      proxy_set_header Host $http_host;
      proxy_pass http://hydra:4444;
    }
  }
}
