server:
  port: 8080
  contextPath: ""
  host: 0.0.0.0

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: snoopy2002
  dbname: basyx
  maxOpenConnections: 50
  maxIdleConnections: 50
  connMaxLifetimeMinutes: 5

