// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/eclipse-basyx/basyx-go-components/internal/common"
)

// AASXAsyncFileServerAPIAPIController binds SSP-002 upload requests.
type AASXAsyncFileServerAPIAPIController struct {
	service            AASXAsyncFileServerAPIAPIServicer
	errorHandler       ErrorHandler
	contextPath        string
	uploadStager       common.UploadStager
	maxUploadSizeBytes int64
}

type AASXAsyncFileServerAPIAPIOption func(*AASXAsyncFileServerAPIAPIController)

func WithAASXAsyncFileServerAPIAPIErrorHandler(handler ErrorHandler) AASXAsyncFileServerAPIAPIOption {
	return func(controller *AASXAsyncFileServerAPIAPIController) { controller.errorHandler = handler }
}

func WithAASXAsyncFileServerUploadStager(stager common.UploadStager, maxUploadSizeBytes int64) AASXAsyncFileServerAPIAPIOption {
	return func(controller *AASXAsyncFileServerAPIAPIController) {
		controller.uploadStager = stager
		controller.maxUploadSizeBytes = maxUploadSizeBytes
	}
}

func NewAASXAsyncFileServerAPIAPIController(service AASXAsyncFileServerAPIAPIServicer, contextPath string, options ...AASXAsyncFileServerAPIAPIOption) *AASXAsyncFileServerAPIAPIController {
	controller := &AASXAsyncFileServerAPIAPIController{
		service: service, errorHandler: DefaultErrorHandler, contextPath: normalizeContextPath(contextPath),
	}
	for _, option := range options {
		option(controller)
	}
	return controller
}

func (controller *AASXAsyncFileServerAPIAPIController) Routes() Routes {
	return Routes{
		"PostAsyncAASXPackage": {
			Method: strings.ToUpper("Post"), Pattern: controller.contextPath + "/packages-async", HandlerFunc: controller.PostAsyncAASXPackage,
		},
	}
}

// PostAsyncAASXPackage initiates an asynchronous upload of an AASX package.
func (controller *AASXAsyncFileServerAPIAPIController) PostAsyncAASXPackage(writer http.ResponseWriter, request *http.Request) {
	if controller.uploadStager == nil {
		controller.errorHandler(writer, request, common.NewInternalServerError("AASXFILES-ASYNCUPLOAD-NOSTAGER upload stager is not configured"), nil)
		return
	}
	upload, err := common.ReadMultipartUpload(writer, request, controller.maxUploadSizeBytes, "file", controller.uploadStager)
	if err != nil {
		controller.errorHandler(writer, request, &ParsingError{Param: "file", Err: err}, nil)
		return
	}
	defer func() { _ = upload.Close() }()

	result, err := controller.service.PostAsyncAASXPackage(request.Context(), upload.File, uploadAASIDs(upload), uploadFileName(upload))
	if err != nil {
		controller.errorHandler(writer, request, err, &result)
		return
	}
	if result.Code == http.StatusAccepted {
		if handle, ok := result.Body.(OperationHandle); ok && handle.HandleId != "" {
			location := "/packages-async/status/" + url.PathEscape(handle.HandleId)
			writer.Header().Set("Location", common.ContextualizeAPIResourceLocation(request, location, "/packages-async"))
		}
	}
	_ = EncodeJSONResponse(result.Body, &result.Code, writer)
}
