// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * DotAAS Part 2 | HTTP/REST | AASX File Server Service Specification
 *
 * The File Server Service Specification as part of the AAS Part 2 specification.
 *
 * API version: V3.2.0_SSP-001
 */

package openapi

import (
	"net/http"
)

// Logger preserves the generated middleware hook for compatibility.
//
// Access logging is configured by the hosting application.
func Logger(inner http.Handler, name string) http.Handler {
	return inner
}
