name: Common Package Tests

on:
  pull_request:
    paths:
      - 'internal/common/**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/common-tests.yml'
      - '**.sql'
  push:
    branches: [main]
    paths:
      - 'internal/common/**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/common-tests.yml'
      - '**.sql'

permissions:
  contents: read

jobs:
  common-tests:
    name: Run Common Package Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # Use the version in go.mod if present; otherwise pin a version
          go-version-file: go.mod
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Run common root package tests
        run: go test -count=1 -v -cover ./internal/common

      - name: Run common async bulk tests
        run: go test -count=1 -v -cover ./internal/common/asyncbulk

      - name: Run common builder tests
        run: go test -count=1 -v -cover ./internal/common/builder

      - name: Run common descriptor tests
        run: go test -count=1 -v -cover ./internal/common/descriptors

      - name: Run common history tests
        run: go test -count=1 -v -cover ./internal/common/history

      - name: Run common JWS tests
        run: go test -count=1 -v -cover ./internal/common/jws

      - name: Run common model tests
        run: go test -count=1 -v -cover ./internal/common/model

      - name: Run common security tests
        run: go test -count=1 -v -cover ./internal/common/security

      - name: Run common model grammar tests
        run: go test github.com/eclipse-basyx/basyx-go-components/internal/common/model/grammar -count=1 -v -cover

      - name: Run common security model tests
        run: |
          cd internal/common/security/unit_tests/model
          go test -count=1 -v -cover

      - name: Run common security abac engine tests
        run: |
          cd internal/common/security/unit_tests/abac_engine
          go test -count=1 -v -cover

      - name: Run common security filter tests
        run: |
          cd internal/common/security/unit_tests/filter_abac_engine
          go test -count=1 -v -cover

      - name: Run common test environment tests
        run: go test -count=1 -v -cover ./internal/common/testenv
