name: Go All Tests

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-all-tests.yml'
      - '**.sql'
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-all-tests.yml'
      - '**.sql'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  all-go-tests:
    name: Run All Go Tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Clean test cache
        run: go clean -testcache

      - name: Run all tests
        run: go test -count=1 -p 1 -v ./...
